//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.MaterialsAccounting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text_ro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_ro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.MaterialsAccounting.Text.ro", typeof(Text_ro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitatea de masura de baza.
        /// </summary>
        internal static string BasicUnitOfMeasure {
            get {
                return ResourceManager.GetString("BasicUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitate de baza.
        /// </summary>
        internal static string BasicUnitOfMeasureShort {
            get {
                return ResourceManager.GetString("BasicUnitOfMeasureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti data de inceput.
        /// </summary>
        internal static string BeginDateRequired {
            get {
                return ResourceManager.GetString("BeginDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticla.
        /// </summary>
        internal static string Bottle {
            get {
                return ResourceManager.GetString("Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutie.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeata.
        /// </summary>
        internal static string Bucket {
            get {
                return ResourceManager.GetString("Bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumabile.
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toate.
        /// </summary>
        internal static string ConsumptionType_All {
            get {
                return ResourceManager.GetString("ConsumptionType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulare comanda.
        /// </summary>
        internal static string ConsumptionType_Canceled {
            get {
                return ResourceManager.GetString("ConsumptionType_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebut.
        /// </summary>
        internal static string ConsumptionType_Defect {
            get {
                return ResourceManager.GetString("ConsumptionType_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentatie personal.
        /// </summary>
        internal static string ConsumptionType_PersonalFood {
            get {
                return ResourceManager.GetString("ConsumptionType_PersonalFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanzari.
        /// </summary>
        internal static string ConsumptionType_Sales {
            get {
                return ResourceManager.GetString("ConsumptionType_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferuri.
        /// </summary>
        internal static string ConsumptionType_Transfers {
            get {
                return ResourceManager.GetString("ConsumptionType_Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensiune container.
        /// </summary>
        internal static string ContainerSize {
            get {
                return ResourceManager.GetString("ContainerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fara recipient.
        /// </summary>
        internal static string ContainerTypeNone {
            get {
                return ResourceManager.GetString("ContainerTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putrezire (mucegai).
        /// </summary>
        internal static string DebitingReason_Corruption {
            get {
                return ResourceManager.GetString("DebitingReason_Corruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termen de valabilitate expirat.
        /// </summary>
        internal static string DebitingReason_Expired {
            get {
                return ResourceManager.GetString("DebitingReason_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoana responsabila.
        /// </summary>
        internal static string DebitingReason_GuiltyPerson {
            get {
                return ResourceManager.GetString("DebitingReason_GuiltyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activitati de marketing.
        /// </summary>
        internal static string DebitingReason_MarketingActivities {
            get {
                return ResourceManager.GetString("DebitingReason_MarketingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj deteriorat.
        /// </summary>
        internal static string DebitingReason_PackageDamaged {
            get {
                return ResourceManager.GetString("DebitingReason_PackageDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa uscata.
        /// </summary>
        internal static string DryWeight {
            get {
                return ResourceManager.GetString("DryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti data de sfarsit.
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura de seara.
        /// </summary>
        internal static string EveningShift {
            get {
                return ResourceManager.GetString("EveningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zilnic.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lunar.
        /// </summary>
        internal static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saptamanal.
        /// </summary>
        internal static string EveryWeek {
            get {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        internal static string Federal {
            get {
                return ResourceManager.GetString("Federal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoarea campului {0} trebuie sa fie pozitiva.
        /// </summary>
        internal static string FieldMustBePositive {
            get {
                return ResourceManager.GetString("FieldMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse finite.
        /// </summary>
        internal static string FinishedProduct {
            get {
                return ResourceManager.GetString("FinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentru toate unitatile.
        /// </summary>
        internal static string ForAllUnits {
            get {
                return ResourceManager.GetString("ForAllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободный вес.
        /// </summary>
        internal static string FreeTara {
            get {
                return ResourceManager.GetString("FreeTara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        internal static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string GramShort {
            get {
                return ResourceManager.GetString("GramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        internal static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiecte inventar.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borcan.
        /// </summary>
        internal static string Jar {
            get {
                return ResourceManager.GetString("Jar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograme.
        /// </summary>
        internal static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string KilogramShort {
            get {
                return ResourceManager.GetString("KilogramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexan 1/1.
        /// </summary>
        internal static string Lexan1 {
            get {
                return ResourceManager.GetString("Lexan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexan 1/2.
        /// </summary>
        internal static string Lexan2 {
            get {
                return ResourceManager.GetString("Lexan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexan 1/3.
        /// </summary>
        internal static string Lexan3 {
            get {
                return ResourceManager.GetString("Lexan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexan 1/6.
        /// </summary>
        internal static string Lexan6 {
            get {
                return ResourceManager.GetString("Lexan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexan 1/9.
        /// </summary>
        internal static string Lexan9 {
            get {
                return ResourceManager.GetString("Lexan9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litri.
        /// </summary>
        internal static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L..
        /// </summary>
        internal static string LiterShort {
            get {
                return ResourceManager.GetString("LiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu este completata denumirea.
        /// </summary>
        internal static string Material_MaterialNameIsRequired {
            get {
                return ResourceManager.GetString("Material_MaterialNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu a fost selectat tipul materiei prime.
        /// </summary>
        internal static string Material_MaterialTypeIsRequired {
            get {
                return ResourceManager.GetString("Material_MaterialTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugimea maxima a campului {1}.
        /// </summary>
        internal static string MaximumFieldLength {
            get {
                return ResourceManager.GetString("MaximumFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Americano.
        /// </summary>
        internal static string MeasureType_Americano {
            get {
                return ResourceManager.GetString("MeasureType_Americano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappuccino.
        /// </summary>
        internal static string MeasureType_Cappuccino {
            get {
                return ResourceManager.GetString("MeasureType_Cappuccino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar mozzarella.
        /// </summary>
        internal static string MeasureType_CheesseCup {
            get {
                return ResourceManager.GetString("MeasureType_CheesseCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espresso.
        /// </summary>
        internal static string MeasureType_Espresso {
            get {
                return ResourceManager.GetString("MeasureType_Espresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar 100 ml.
        /// </summary>
        internal static string MeasureType_Glass100Ml {
            get {
                return ResourceManager.GetString("MeasureType_Glass100Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar 200 ml.
        /// </summary>
        internal static string MeasureType_Glass200Ml {
            get {
                return ResourceManager.GetString("MeasureType_Glass200Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucati.
        /// </summary>
        internal static string MeasureType_Hickey {
            get {
                return ResourceManager.GetString("MeasureType_Hickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latte.
        /// </summary>
        internal static string MeasureType_Latte {
            get {
                return ResourceManager.GetString("MeasureType_Latte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciupitura.
        /// </summary>
        internal static string MeasureType_Pinch {
            get {
                return ResourceManager.GetString("MeasureType_Pinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portii bauturi.
        /// </summary>
        internal static string MeasureType_PortionDrink {
            get {
                return ResourceManager.GetString("MeasureType_PortionDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie in Pizza/Gustare/Sandwich.
        /// </summary>
        internal static string MeasureType_PortionForProduct {
            get {
                return ResourceManager.GetString("MeasureType_PortionForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie inghetata.
        /// </summary>
        internal static string MeasureType_PortionIceCream {
            get {
                return ResourceManager.GetString("MeasureType_PortionIceCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie nuggets-uril.
        /// </summary>
        internal static string MeasureType_PortionNuggets {
            get {
                return ResourceManager.GetString("MeasureType_PortionNuggets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порция картошки.
        /// </summary>
        internal static string MeasureType_PortionPotatoes {
            get {
                return ResourceManager.GetString("MeasureType_PortionPotatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie somon.
        /// </summary>
        internal static string MeasureType_PortionSalmon {
            get {
                return ResourceManager.GetString("MeasureType_PortionSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie creveti.
        /// </summary>
        internal static string MeasureType_PortionShrimp {
            get {
                return ResourceManager.GetString("MeasureType_PortionShrimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apasari pistol.
        /// </summary>
        internal static string MeasureType_PressingGun {
            get {
                return ResourceManager.GetString("MeasureType_PressingGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scuturare.
        /// </summary>
        internal static string MeasureType_Shake {
            get {
                return ResourceManager.GetString("MeasureType_Shake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice.
        /// </summary>
        internal static string MeasureType_Slice {
            get {
                return ResourceManager.GetString("MeasureType_Slice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polonic.
        /// </summary>
        internal static string MeasureType_SoupLadle {
            get {
                return ResourceManager.GetString("MeasureType_SoupLadle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gustare.
        /// </summary>
        internal static string MeasureTypeVariation_Breakfast {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar 100 ml.
        /// </summary>
        internal static string MeasureTypeVariation_Glass100Ml {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass100Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string MeasureTypeVariation_Glass100Ml1 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass100Ml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string MeasureTypeVariation_Glass100Ml1_2 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass100Ml1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/4.
        /// </summary>
        internal static string MeasureTypeVariation_Glass100Ml1_4 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass100Ml1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3/4.
        /// </summary>
        internal static string MeasureTypeVariation_Glass100Ml3_4 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass100Ml3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar 200 ml.
        /// </summary>
        internal static string MeasureTypeVariation_Glass200Ml {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Glass200Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string MeasureTypeVariation_HalfOfLargeGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_HalfOfLargeGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string MeasureTypeVariation_HalfOfMediumGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_HalfOfMediumGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string MeasureTypeVariation_HalfOfSmallGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_HalfOfSmallGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bucata.
        /// </summary>
        internal static string MeasureTypeVariation_HickeyOneHickey {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_HickeyOneHickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar mare.
        /// </summary>
        internal static string MeasureTypeVariation_LargeGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_LargeGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar mediu.
        /// </summary>
        internal static string MeasureTypeVariation_MediumGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_MediumGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ciupitura.
        /// </summary>
        internal static string MeasureTypeVariation_PinchOnePinch {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PinchOnePinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie 14 buc.
        /// </summary>
        internal static string MeasureTypeVariation_Portion14Pieces {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Portion14Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie dodomix.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDoDoMixNugget {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDoDoMixNugget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie dodomix.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDoDoMixPotatoes {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDoDoMixPotatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,2 l.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDrink0_2L {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDrink0_2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,3 l.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDrink0_3L {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDrink0_3L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,5 l.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDrink0_5L {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDrink0_5L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,6 l.
        /// </summary>
        internal static string MeasureTypeVariation_PortionDrink0_6L {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionDrink0_6L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza 25.
        /// </summary>
        internal static string MeasureTypeVariation_PortionForPizza25 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionForPizza25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza 30.
        /// </summary>
        internal static string MeasureTypeVariation_PortionForPizza30 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionForPizza30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza 35.
        /// </summary>
        internal static string MeasureTypeVariation_PortionForPizza35 {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionForPizza35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandwich.
        /// </summary>
        internal static string MeasureTypeVariation_PortionForSandwich {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionForSandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie inghetata.
        /// </summary>
        internal static string MeasureTypeVariation_PortionIceCream {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionIceCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O portie.
        /// </summary>
        internal static string MeasureTypeVariation_PortionIceCreamOne {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionIceCreamOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,05 l.
        /// </summary>
        internal static string MeasureTypeVariation_PortionOfDrink0_05L {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionOfDrink0_05L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O portie.
        /// </summary>
        internal static string MeasureTypeVariation_PortionSalmonOne {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionSalmonOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O portie.
        /// </summary>
        internal static string MeasureTypeVariation_PortionShrimpOne {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionShrimpOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portie wedges.
        /// </summary>
        internal static string MeasureTypeVariation_PortionVillage {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PortionVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O apasare.
        /// </summary>
        internal static string MeasureTypeVariation_PressingGunOnePress {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_PressingGunOnePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O scuturare.
        /// </summary>
        internal static string MeasureTypeVariation_ShakeOneShake {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_ShakeOneShake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice.
        /// </summary>
        internal static string MeasureTypeVariation_Slice {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_Slice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahar mic.
        /// </summary>
        internal static string MeasureTypeVariation_SmallGlass {
            get {
                return ResourceManager.GetString("MeasureTypeVariation_SmallGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alegeti forma persoanei juridice.
        /// </summary>
        internal static string Message_RequiredOrganizationType {
            get {
                return ResourceManager.GetString("Message_RequiredOrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicati forma de functionare.
        /// </summary>
        internal static string Message_RequiredPaymentOption {
            get {
                return ResourceManager.GetString("Message_RequiredPaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicati denumirea companiei furnizorului.
        /// </summary>
        internal static string Message_RequiredSupplierName {
            get {
                return ResourceManager.GetString("Message_RequiredSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metru.
        /// </summary>
        internal static string Metr {
            get {
                return ResourceManager.GetString("Metr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string MetrShort {
            get {
                return ResourceManager.GetString("MetrShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mililitri.
        /// </summary>
        internal static string Milliliter {
            get {
                return ResourceManager.GetString("Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ml..
        /// </summary>
        internal static string MilliliterShort {
            get {
                return ResourceManager.GetString("MilliliterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura de dimineata.
        /// </summary>
        internal static string MorningShift {
            get {
                return ResourceManager.GetString("MorningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura de noapte.
        /// </summary>
        internal static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punga.
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalare.
        /// </summary>
        internal static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaje.
        /// </summary>
        internal static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termen de plata.
        /// </summary>
        internal static string PaymentOption_Deferment {
            get {
                return ResourceManager.GetString("PaymentOption_Deferment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plata avans.
        /// </summary>
        internal static string PaymentOption_Prepaid {
            get {
                return ResourceManager.GetString("PaymentOption_Prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucati.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buc..
        /// </summary>
        internal static string QuantityShort {
            get {
                return ResourceManager.GetString("QuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semifabricat.
        /// </summary>
        internal static string SemiFinishedProduct {
            get {
                return ResourceManager.GetString("SemiFinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sac.
        /// </summary>
        internal static string Tara_Bag {
            get {
                return ResourceManager.GetString("Tara_Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butelie.
        /// </summary>
        internal static string Tara_Balloon {
            get {
                return ResourceManager.GetString("Tara_Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticla.
        /// </summary>
        internal static string Tara_Bottle {
            get {
                return ResourceManager.GetString("Tara_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutie.
        /// </summary>
        internal static string Tara_Box {
            get {
                return ResourceManager.GetString("Tara_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeata.
        /// </summary>
        internal static string Tara_Bucket {
            get {
                return ResourceManager.GetString("Tara_Bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conserva.
        /// </summary>
        internal static string Tara_CuppingGlass {
            get {
                return ResourceManager.GetString("Tara_CuppingGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butoi.
        /// </summary>
        internal static string Tara_Kega {
            get {
                return ResourceManager.GetString("Tara_Kega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaje.
        /// </summary>
        internal static string Tara_Packing {
            get {
                return ResourceManager.GetString("Tara_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola.
        /// </summary>
        internal static string Tara_Roll {
            get {
                return ResourceManager.GetString("Tara_Roll", resourceCulture);
            }
        }
    }
}
