//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Departments {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Departments.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласовано.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call-центр.
        /// </summary>
        public static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обращение по умолчанию.
        /// </summary>
        public static string ClientTreatment_DefaultName {
            get {
                return ResourceManager.GetString("ClientTreatment_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по имени.
        /// </summary>
        public static string ClientTreatment_Name {
            get {
                return ResourceManager.GetString("ClientTreatment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to случайное изображение.
        /// </summary>
        public static string ClientTreatment_RandomImage {
            get {
                return ResourceManager.GetString("ClientTreatment_RandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыто.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу удалить страну..
        /// </summary>
        public static string Error_CantRemoveCountry {
            get {
                return ResourceManager.GetString("Error_CantRemoveCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Название на транслите&quot; должно содержать только цифры и буквы латинского алфавита.
        /// </summary>
        public static string Error_TranslitAlias {
            get {
                return ResourceManager.GetString("Error_TranslitAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите псевдоним.
        /// </summary>
        public static string Error_UnitAliasIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitAliasIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите Согласование открытия.
        /// </summary>
        public static string Error_UnitApproveIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitApproveIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно указаны координаты отдела.
        /// </summary>
        public static string Error_UnitCoordinateXRange {
            get {
                return ResourceManager.GetString("Error_UnitCoordinateXRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно указаны координаты отдела.
        /// </summary>
        public static string Error_UnitCoordinateYRange {
            get {
                return ResourceManager.GetString("Error_UnitCoordinateYRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите вид деятельности отдела.
        /// </summary>
        public static string Error_UnitOrderTypesIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitOrderTypesIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите организацию.
        /// </summary>
        public static string Error_UnitOrganizationRequired {
            get {
                return ResourceManager.GetString("Error_UnitOrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин для публичных экранов.
        /// </summary>
        public static string Error_UnitPublicMenuLoginIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitPublicMenuLoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно указана площадь помещения.
        /// </summary>
        public static string Error_UnitSquareRange {
            get {
                return ResourceManager.GetString("Error_UnitSquareRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите состояние отдела.
        /// </summary>
        public static string Error_UnitStateIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitStateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин для трекинга.
        /// </summary>
        public static string Error_UnitTrackingLoginIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitTrackingLoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите тип отдела.
        /// </summary>
        public static string Error_UnitTypeIsRequired {
            get {
                return ResourceManager.GetString("Error_UnitTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фабрика полуфабрикатов.
        /// </summary>
        public static string FactorySemis {
            get {
                return ResourceManager.GetString("FactorySemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название.
        /// </summary>
        public static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не согласовано.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офис.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиццерия.
        /// </summary>
        public static string Pizzeria {
            get {
                return ResourceManager.GetString("Pizzeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производственно-распределительный цех.
        /// </summary>
        public static string ProductionDistributionWorkshop {
            get {
                return ResourceManager.GetString("ProductionDistributionWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис доставки.
        /// </summary>
        public static string ServiceDelivery {
            get {
                return ResourceManager.GetString("ServiceDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоро открытие.
        /// </summary>
        public static string SoonOpening {
            get {
                return ResourceManager.GetString("SoonOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное свойство {0}.
        /// </summary>
        public static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Вид деятельности&quot; должно быть заполнено.
        /// </summary>
        public static string ValidationRequiredOrderType {
            get {
                return ResourceManager.GetString("ValidationRequiredOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
    }
}
