//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Accounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Accounts.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бухгалтер.
        /// </summary>
        public static string Accountant {
            get {
                return ResourceManager.GetString("Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все пиццерии.
        /// </summary>
        public static string AllPizzerias {
            get {
                return ResourceManager.GetString("AllPizzerias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все причины.
        /// </summary>
        public static string AllReasons {
            get {
                return ResourceManager.GetString("AllReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За приглашение друзей.
        /// </summary>
        public static string BonusAccruedByFriends {
            get {
                return ResourceManager.GetString("BonusAccruedByFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начислено &quot;Додо рублей&quot;.
        /// </summary>
        public static string BonusAccruedTitle {
            get {
                return ResourceManager.GetString("BonusAccruedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string BonusAll {
            get {
                return ResourceManager.GetString("BonusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент от заказов.
        /// </summary>
        public static string BonusPercentage {
            get {
                return ResourceManager.GetString("BonusPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент от заказов друзей.
        /// </summary>
        public static string BonusPercentageFromFriends {
            get {
                return ResourceManager.GetString("BonusPercentageFromFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент использованных &quot;Додо рублей&quot; от выручки.
        /// </summary>
        public static string BonusSpentPercentage {
            get {
                return ResourceManager.GetString("BonusSpentPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потрачено &quot;Додо рублей&quot;.
        /// </summary>
        public static string BonusSpentTitle {
            get {
                return ResourceManager.GetString("BonusSpentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen CT-S310II.
        /// </summary>
        public static string CashBoxModel_Citizen {
            get {
                return ResourceManager.GetString("CashBoxModel_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассир ресторана.
        /// </summary>
        public static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по имени.
        /// </summary>
        public static string ClientTreatment_Name {
            get {
                return ResourceManager.GetString("ClientTreatment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to случайное изображение.
        /// </summary>
        public static string ClientTreatment_RandomImage {
            get {
                return ResourceManager.GetString("ClientTreatment_RandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курьер.
        /// </summary>
        public static string Courier {
            get {
                return ResourceManager.GetString("Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табло мотивации курьеров.
        /// </summary>
        public static string CourierMotivationScreen {
            get {
                return ResourceManager.GetString("CourierMotivationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вышел срок годности.
        /// </summary>
        public static string DebitingReason_Expired {
            get {
                return ResourceManager.GetString("DebitingReason_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виновное лицо.
        /// </summary>
        public static string DebitingReason_GuiltyPerson {
            get {
                return ResourceManager.GetString("DebitingReason_GuiltyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повреждение упаковки.
        /// </summary>
        public static string DebitingReason_PackageDamaged {
            get {
                return ResourceManager.GetString("DebitingReason_PackageDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассир доставки.
        /// </summary>
        public static string DeliveryCashier {
            get {
                return ResourceManager.GetString("DeliveryCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор подразделения.
        /// </summary>
        public static string DepartmentAdmin {
            get {
                return ResourceManager.GetString("DepartmentAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчик.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додо Контроллинг.
        /// </summary>
        public static string DodoControl {
            get {
                return ResourceManager.GetString("DodoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен некорректный адрес электронной почты.
        /// </summary>
        public static string EmailIsNotValidMessage {
            get {
                return ResourceManager.GetString("EmailIsNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табло сотрудники.
        /// </summary>
        public static string EmployeesOnShiftScreen {
            get {
                return ResourceManager.GetString("EmployeesOnShiftScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная цена. Должна быть кратна 100..
        /// </summary>
        public static string Error_IncorrectPriceInHundred {
            get {
                return ResourceManager.GetString("Error_IncorrectPriceInHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная цена. Должна быть кратна 1..
        /// </summary>
        public static string Error_IncorrectPriceInOneNumber {
            get {
                return ResourceManager.GetString("Error_IncorrectPriceInOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспресс продукты.
        /// </summary>
        public static string ExpressProductsScreen {
            get {
                return ResourceManager.GetString("ExpressProductsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Федеральный.
        /// </summary>
        public static string Federal {
            get {
                return ResourceManager.GetString("Federal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для всех отделов.
        /// </summary>
        public static string ForAllUnits {
            get {
                return ResourceManager.GetString("ForAllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центральный менеджер офиса - франчайзи.
        /// </summary>
        public static string FranchiseeOfficeManager {
            get {
                return ResourceManager.GetString("FranchiseeOfficeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приход.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатель.
        /// </summary>
        public static string IndexValue {
            get {
                return ResourceManager.GetString("IndexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер офиса - инвестор.
        /// </summary>
        public static string InvestorOfficeManager {
            get {
                return ResourceManager.GetString("InvestorOfficeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табло мотивации кухни.
        /// </summary>
        public static string KitchenMotivationScreen {
            get {
                return ResourceManager.GetString("KitchenMotivationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин может состоять только из латинских букв, цифр и символов, нижнего подчеркивания и точки.
        /// </summary>
        public static string LoginNotCorrect {
            get {
                return ResourceManager.GetString("LoginNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не может быть пустым.
        /// </summary>
        public static string LoginNotRequired {
            get {
                return ResourceManager.GetString("LoginNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не может быть длиннее 50 символов.
        /// </summary>
        public static string LoginTooLong {
            get {
                return ResourceManager.GetString("LoginTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер бонусной системы.
        /// </summary>
        public static string LoyaltyManager {
            get {
                return ResourceManager.GetString("LoyaltyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление ТП.
        /// </summary>
        public static string MysteryShopperManager {
            get {
                return ResourceManager.GetString("MysteryShopperManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые клиенты.
        /// </summary>
        public static string NewClients {
            get {
                return ResourceManager.GetString("NewClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество клиентов, привлеченных Бонусной программой.
        /// </summary>
        public static string NewClientsByLoyaltyTotalCount {
            get {
                return ResourceManager.GetString("NewClientsByLoyaltyTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество новых клиентов.
        /// </summary>
        public static string NewClientsTotalCount {
            get {
                return ResourceManager.GetString("NewClientsTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер офиса.
        /// </summary>
        public static string OfficeManager {
            get {
                return ResourceManager.GetString("OfficeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть пустым.
        /// </summary>
        public static string PasswordNotRequired {
            get {
                return ResourceManager.GetString("PasswordNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть длиннее 100 символов.
        /// </summary>
        public static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиццамейкер.
        /// </summary>
        public static string Pizzamaker {
            get {
                return ResourceManager.GetString("Pizzamaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя в предложном падеже.
        /// </summary>
        public static string PrepositionalAliasCaption {
            get {
                return ResourceManager.GetString("PrepositionalAliasCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичный.
        /// </summary>
        public static string PublicCaption {
            get {
                return ResourceManager.GetString("PublicCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичные экраны.
        /// </summary>
        public static string PublicPages {
            get {
                return ResourceManager.GetString("PublicPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списание сырья.
        /// </summary>
        public static string Report_MaterialDebiting {
            get {
                return ResourceManager.GetString("Report_MaterialDebiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табло ресторана.
        /// </summary>
        public static string RestaurantScreen {
            get {
                return ResourceManager.GetString("RestaurantScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказов новых клиентов, привлеченных Бонусной программой.
        /// </summary>
        public static string RevenueNewClientsByLoyaltyTotal {
            get {
                return ResourceManager.GetString("RevenueNewClientsByLoyaltyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ревизия от {0}.
        /// </summary>
        public static string RevisionAt {
            get {
                return ResourceManager.GetString("RevisionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ревизор.
        /// </summary>
        public static string Revisor {
            get {
                return ResourceManager.GetString("Revisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центральный администратор.
        /// </summary>
        public static string RootAdmin {
            get {
                return ResourceManager.GetString("RootAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центральный менеджер офиса.
        /// </summary>
        public static string RootOfficeManager {
            get {
                return ResourceManager.GetString("RootOfficeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центральный оператор.
        /// </summary>
        public static string RootOperator {
            get {
                return ResourceManager.GetString("RootOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер смены.
        /// </summary>
        public static string ShiftManager {
            get {
                return ResourceManager.GetString("ShiftManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрина.
        /// </summary>
        public static string ShopWindowItemsScreen {
            get {
                return ResourceManager.GetString("ShopWindowItemsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовый бонус.
        /// </summary>
        public static string StartBonus {
            get {
                return ResourceManager.GetString("StartBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учтённые потери.
        /// </summary>
        public static string TakenLosses {
            get {
                return ResourceManager.GetString("TakenLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неучтённые потери.
        /// </summary>
        public static string Title_LossesAndExceesReport {
            get {
                return ResourceManager.GetString("Title_LossesAndExceesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бонусная программа.
        /// </summary>
        public static string Title_LoyaltyReport {
            get {
                return ResourceManager.GetString("Title_LoyaltyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг.
        /// </summary>
        public static string TrackingManager {
            get {
                return ResourceManager.GetString("TrackingManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Закуски.
        /// </summary>
        public static string TrackingManagerOnColdAssemblyTable {
            get {
                return ResourceManager.GetString("TrackingManagerOnColdAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Тесто.
        /// </summary>
        public static string TrackingManagerOnDoughTable {
            get {
                return ResourceManager.GetString("TrackingManagerOnDoughTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Линия.
        /// </summary>
        public static string TrackingManagerOnHotAssemblyTable {
            get {
                return ResourceManager.GetString("TrackingManagerOnHotAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Курьеры.
        /// </summary>
        public static string TrackingManagerOnOrdersToDelivery {
            get {
                return ResourceManager.GetString("TrackingManagerOnOrdersToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Ресторан.
        /// </summary>
        public static string TrackingManagerOnOrdersToStationary {
            get {
                return ResourceManager.GetString("TrackingManagerOnOrdersToStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Печь.
        /// </summary>
        public static string TrackingManagerOnOvenTable {
            get {
                return ResourceManager.GetString("TrackingManagerOnOvenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Упаковка.
        /// </summary>
        public static string TrackingManagerOnPackingTable {
            get {
                return ResourceManager.GetString("TrackingManagerOnPackingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трекинг - Списание кусочков.
        /// </summary>
        public static string TrackingManagerOnSliceDebiting {
            get {
                return ResourceManager.GetString("TrackingManagerOnSliceDebiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТВ-борды.
        /// </summary>
        public static string TvBoard {
            get {
                return ResourceManager.GetString("TvBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор подразделения.
        /// </summary>
        public static string UnitateAdmin {
            get {
                return ResourceManager.GetString("UnitateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана роль.
        /// </summary>
        public static string UserRoleNotExist {
            get {
                return ResourceManager.GetString("UserRoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран отдел.
        /// </summary>
        public static string UserUnitNotRequired {
            get {
                return ResourceManager.GetString("UserUnitNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер транзакций Я.Деньги.
        /// </summary>
        public static string YandexTransactionManager {
            get {
                return ResourceManager.GetString("YandexTransactionManager", resourceCulture);
            }
        }
    }
}
