//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Promotion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Promotion.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная.
        /// </summary>
        public static string AdditionalSaleTypeActive {
            get {
                return ResourceManager.GetString("AdditionalSaleTypeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная (всплывающее окно).
        /// </summary>
        public static string AdditionalSaleTypeActiveTitle {
            get {
                return ResourceManager.GetString("AdditionalSaleTypeActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассивная.
        /// </summary>
        public static string AdditionalSaleTypePassive {
            get {
                return ResourceManager.GetString("AdditionalSaleTypePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассивная (в блоке на странице корзины).
        /// </summary>
        public static string AdditionalSaleTypePassiveTitle {
            get {
                return ResourceManager.GetString("AdditionalSaleTypePassiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ALISA {
            get {
                return ResourceManager.GetString("ALISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все дни.
        /// </summary>
        public static string AllDays {
            get {
                return ResourceManager.GetString("AllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма без НДС.
        /// </summary>
        public static string AmountWithOutNDS {
            get {
                return ResourceManager.GetString("AmountWithOutNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний чек.
        /// </summary>
        public static string AverageCheck {
            get {
                return ResourceManager.GetString("AverageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя загрузка.
        /// </summary>
        public static string AverageWorkLoad {
            get {
                return ResourceManager.GetString("AverageWorkLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долго.
        /// </summary>
        public static string BadBonus {
            get {
                return ResourceManager.GetString("BadBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена по центру.
        /// </summary>
        public static string BannerPosition_Center {
            get {
                return ResourceManager.GetString("BannerPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена слева.
        /// </summary>
        public static string BannerPosition_Left {
            get {
                return ResourceManager.GetString("BannerPosition_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без цены.
        /// </summary>
        public static string BannerPosition_None {
            get {
                return ResourceManager.GetString("BannerPosition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена справа.
        /// </summary>
        public static string BannerPosition_Right {
            get {
                return ResourceManager.GetString("BannerPosition_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс цены.
        /// </summary>
        public static string BannerPricePrefix {
            get {
                return ResourceManager.GetString("BannerPricePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходные данные.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция.
        /// </summary>
        public static string BonusAction {
            get {
                return ResourceManager.GetString("BonusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть любой продукт из списка &quot;{0}&quot;.
        /// </summary>
        public static string BonusAction_ConditionDescription_AnyProduct {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_AnyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть любые продукты в количестве {0} из списка {1}.
        /// </summary>
        public static string BonusAction_ConditionDescription_AnyProductInAmount {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_AnyProductInAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть большие пиццы в количестве не менее {0}.
        /// </summary>
        public static string BonusAction_ConditionDescription_BigPizzas {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_BigPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть комбо &quot;{0}&quot; в количестве не менее {1}.
        /// </summary>
        public static string BonusAction_ConditionDescription_Combo {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть комбо &quot;{0}&quot; в количестве не менее {1} каждый.
        /// </summary>
        public static string BonusAction_ConditionDescription_ComboMultiple {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_ComboMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}   ObjectType: {1}   ConcreteObject: {2}   ConditionSize: {3}.
        /// </summary>
        public static string BonusAction_ConditionDescription_Default {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть продукты из категории &quot;{0}&quot; в количестве не менее {1}.
        /// </summary>
        public static string BonusAction_ConditionDescription_FromCategory {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_FromCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть средние пиццы в количестве не менее {0}.
        /// </summary>
        public static string BonusAction_ConditionDescription_MediumPizzas {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_MediumPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть продукт &quot;{0}&quot; в количестве не менее {1}.
        /// </summary>
        public static string BonusAction_ConditionDescription_ProductInAmount {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_ProductInAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть продукты &quot;{0}&quot; в количестве не менее {1} каждый.
        /// </summary>
        public static string BonusAction_ConditionDescription_ProductInAmountEach {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_ProductInAmountEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе есть маленькие пиццы в количестве не менее {0}.
        /// </summary>
        public static string BonusAction_ConditionDescription_SmallPizzas {
            get {
                return ResourceManager.GetString("BonusAction_ConditionDescription_SmallPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание акции.
        /// </summary>
        public static string BonusActionDescription {
            get {
                return ResourceManager.GetString("BonusActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направленность.
        /// </summary>
        public static string BonusActionEndPoint {
            get {
                return ResourceManager.GetString("BonusActionEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название акции.
        /// </summary>
        public static string BonusActionName {
            get {
                return ResourceManager.GetString("BonusActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет: Расчеты с КЦ посуточно.
        /// </summary>
        public static string CallCenterDailyReportXmlHeader {
            get {
                return ResourceManager.GetString("CallCenterDailyReportXmlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет: Расчеты с КЦ.
        /// </summary>
        public static string CallCenterReportXmlHeader {
            get {
                return ResourceManager.GetString("CallCenterReportXmlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассовые смены:.
        /// </summary>
        public static string CashBoxShifts {
            get {
                return ResourceManager.GetString("CashBoxShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начинка, холодный.
        /// </summary>
        public static string ColdAssemblyTable {
            get {
                return ResourceManager.GetString("ColdAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расходники.
        /// </summary>
        public static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во отработанных часов.
        /// </summary>
        public static string CountWorkedHours {
            get {
                return ResourceManager.GetString("CountWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курьер.
        /// </summary>
        public static string Courier {
            get {
                return ResourceManager.GetString("Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер курьера.
        /// </summary>
        public static string CourierNumber {
            get {
                return ResourceManager.GetString("CourierNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата возобновления.
        /// </summary>
        public static string DateBeginSale {
            get {
                return ResourceManager.GetString("DateBeginSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В конкретный день.
        /// </summary>
        public static string DateFilter_Day {
            get {
                return ResourceManager.GetString("DateFilter_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дням недели.
        /// </summary>
        public static string DateFilter_DayOfWeek {
            get {
                return ResourceManager.GetString("DateFilter_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        public static string DateFilter_Period {
            get {
                return ResourceManager.GetString("DateFilter_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период дат:.
        /// </summary>
        public static string DatePeriod {
            get {
                return ResourceManager.GetString("DatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата остановки.
        /// </summary>
        public static string DateStopSale {
            get {
                return ResourceManager.GetString("DateStopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата\время.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция.
        /// </summary>
        public static string DefectiveStage {
            get {
                return ResourceManager.GetString("DefectiveStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брак.
        /// </summary>
        public static string DefectProduct {
            get {
                return ResourceManager.GetString("DefectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина просрочки.
        /// </summary>
        public static string DelayReason {
            get {
                return ResourceManager.GetString("DelayReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресс доставки.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка и ресторан.
        /// </summary>
        public static string DeliveryAndStationary {
            get {
                return ResourceManager.GetString("DeliveryAndStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор доставки.
        /// </summary>
        public static string DeliverySectorName {
            get {
                return ResourceManager.GetString("DeliverySectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зона доставки.
        /// </summary>
        public static string DeliveryZone {
            get {
                return ResourceManager.GetString("DeliveryZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется отправка.
        /// </summary>
        public static string DistributionStatusSending {
            get {
                return ResourceManager.GetString("DistributionStatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание.
        /// </summary>
        public static string DistributionStatusWaiting {
            get {
                return ResourceManager.GetString("DistributionStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        public static string DistributionStatusСompleted {
            get {
                return ResourceManager.GetString("DistributionStatusСompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толстое 25.
        /// </summary>
        public static string Dough25 {
            get {
                return ResourceManager.GetString("Dough25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толстое 30.
        /// </summary>
        public static string Dough30 {
            get {
                return ResourceManager.GetString("Dough30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тонкое 30.
        /// </summary>
        public static string Dough30Thin {
            get {
                return ResourceManager.GetString("Dough30Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толстое 35.
        /// </summary>
        public static string Dough35 {
            get {
                return ResourceManager.GetString("Dough35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тонкое 35.
        /// </summary>
        public static string Dough35Thin {
            get {
                return ResourceManager.GetString("Dough35Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тесто.
        /// </summary>
        public static string DoughTable {
            get {
                return ResourceManager.GetString("DoughTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        public static string EmployeeDateFormat {
            get {
                return ResourceManager.GetString("EmployeeDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string EmployeeTimeFormat {
            get {
                return ResourceManager.GetString("EmployeeTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сотрудника.
        /// </summary>
        public static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечная точка.
        /// </summary>
        public static string EndPointType {
            get {
                return ResourceManager.GetString("EndPointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата возобновления.
        /// </summary>
        public static string EndStopSale {
            get {
                return ResourceManager.GetString("EndStopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счете клиента недостаточно средств для списания.
        /// </summary>
        public static string ErrorMessage_CancelAccuralToMysteryShopper {
            get {
                return ResourceManager.GetString("ErrorMessage_CancelAccuralToMysteryShopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция запрещена (Некорректный ID клиента).
        /// </summary>
        public static string ErrorMessage_InvalidClientId {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMessage_NeedEmailForReport {
            get {
                return ResourceManager.GetString("ErrorMessage_NeedEmailForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно денег на счету.
        /// </summary>
        public static string ErrorMessage_NotEnoughMoney {
            get {
                return ResourceManager.GetString("ErrorMessage_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакция не найдена.
        /// </summary>
        public static string ErrorMessage_TransactionNotFond {
            get {
                return ResourceManager.GetString("ErrorMessage_TransactionNotFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ежедневная.
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ежемесячная.
        /// </summary>
        public static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа ({0}) меньше потраченных додолларов ({1})..
        /// </summary>
        public static string ExceptionMessageTemplateApplyDodollars {
            get {
                return ResourceManager.GetString("ExceptionMessageTemplateApplyDodollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исключая.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to исключая уволенных сотрудников.
        /// </summary>
        public static string ExcludeDismissedEmployees {
            get {
                return ResourceManager.GetString("ExcludeDismissedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочено.
        /// </summary>
        public static string ExpiredOrdersCount {
            get {
                return ResourceManager.GetString("ExpiredOrdersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Filter_PizzeriaLoadByOrders {
            get {
                return ResourceManager.GetString("Filter_PizzeriaLoadByOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукты.
        /// </summary>
        public static string Filter_PizzeriaLoadByProducts {
            get {
                return ResourceManager.GetString("Filter_PizzeriaLoadByProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По категории продукта.
        /// </summary>
        public static string Filter_ProductsByCategories {
            get {
                return ResourceManager.GetString("Filter_ProductsByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По типу продукта.
        /// </summary>
        public static string Filter_ProductsByTypes {
            get {
                return ResourceManager.GetString("Filter_ProductsByTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовая продукция.
        /// </summary>
        public static string FinishedProduct {
            get {
                return ResourceManager.GetString("FinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата первого заказа.
        /// </summary>
        public static string FirstOrderDate {
            get {
                return ResourceManager.GetString("FirstOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время первого заказа.
        /// </summary>
        public static string FirstOrderTime {
            get {
                return ResourceManager.GetString("FirstOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятницы.
        /// </summary>
        public static string Fridays {
            get {
                return ResourceManager.GetString("Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сред.
        /// </summary>
        public static string FunctionFilter_Avg {
            get {
                return ResourceManager.GetString("FunctionFilter_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to макс.
        /// </summary>
        public static string FunctionFilter_Max {
            get {
                return ResourceManager.GetString("FunctionFilter_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин.
        /// </summary>
        public static string FunctionFilter_Min {
            get {
                return ResourceManager.GetString("FunctionFilter_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандарт.
        /// </summary>
        public static string GoodBonus {
            get {
                return ResourceManager.GetString("GoodBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грамм.
        /// </summary>
        public static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гр..
        /// </summary>
        public static string GramShort {
            get {
                return ResourceManager.GetString("GramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to праздники.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начинка,горячий.
        /// </summary>
        public static string HotAssemblyTable {
            get {
                return ResourceManager.GetString("HotAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дома.
        /// </summary>
        public static string Houses {
            get {
                return ResourceManager.GetString("Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ингредиент.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В очереди.
        /// </summary>
        public static string InQueue {
            get {
                return ResourceManager.GetString("InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентарь.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кг.
        /// </summary>
        public static string Kg {
            get {
                return ResourceManager.GetString("Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Килограмм.
        /// </summary>
        public static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кг..
        /// </summary>
        public static string KilogramShort {
            get {
                return ResourceManager.GetString("KilogramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string LabourCostShort {
            get {
                return ResourceManager.GetString("LabourCostShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последнего заказа.
        /// </summary>
        public static string LastOrderDate {
            get {
                return ResourceManager.GetString("LastOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время последнего заказа.
        /// </summary>
        public static string LastOrderTime {
            get {
                return ResourceManager.GetString("LastOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Литр.
        /// </summary>
        public static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Л..
        /// </summary>
        public static string LiterShort {
            get {
                return ResourceManager.GetString("LiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нас. пункт.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгое приготовление, %.
        /// </summary>
        public static string LongPreparationProduct {
            get {
                return ResourceManager.GetString("LongPreparationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ед.изм..
        /// </summary>
        public static string MeasureUnit {
            get {
                return ResourceManager.GetString("MeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недействительный промокод.
        /// </summary>
        public static string Message_InvalidPromoCode {
            get {
                return ResourceManager.GetString("Message_InvalidPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задан некорректный формат времени.
        /// </summary>
        public static string Message_InvalidTime {
            get {
                return ResourceManager.GetString("Message_InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано ни одно подразделение.
        /// </summary>
        public static string Message_UnitIdsRequired {
            get {
                return ResourceManager.GetString("Message_UnitIdsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метапродукт.
        /// </summary>
        public static string MetaProduct {
            get {
                return ResourceManager.GetString("MetaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ расчета.
        /// </summary>
        public static string MethodOfCalculation {
            get {
                return ResourceManager.GetString("MethodOfCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Миллилитр.
        /// </summary>
        public static string Milliliter {
            get {
                return ResourceManager.GetString("Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мл..
        /// </summary>
        public static string MilliliterShort {
            get {
                return ResourceManager.GetString("MilliliterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понедельники.
        /// </summary>
        public static string Mondays {
            get {
                return ResourceManager.GetString("Mondays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to января,февраля,марта,апреля,мая,июня,июля,августа,сентября,октября,ноября,декабря.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НДС,%.
        /// </summary>
        public static string NDS {
            get {
                return ResourceManager.GetString("NDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейтральный интервал.
        /// </summary>
        public static string NormalBonus {
            get {
                return ResourceManager.GetString("NormalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На м2 зала.
        /// </summary>
        public static string OnHallSquare {
            get {
                return ResourceManager.GetString("OnHallSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только выходные.
        /// </summary>
        public static string OnlyWeekDays {
            get {
                return ResourceManager.GetString("OnlyWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только будни.
        /// </summary>
        public static string OnlyWorkDays {
            get {
                return ResourceManager.GetString("OnlyWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество срабатываний.
        /// </summary>
        public static string OperationCount {
            get {
                return ResourceManager.GetString("OperationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа.
        /// </summary>
        public static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заказа.
        /// </summary>
        public static string OrderDateOfReceipt {
            get {
                return ResourceManager.GetString("OrderDateOfReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиций.
        /// </summary>
        public static string OrderLinesCount {
            get {
                return ResourceManager.GetString("OrderLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № заказа.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор заказа.
        /// </summary>
        public static string OrderOperator {
            get {
                return ResourceManager.GetString("OrderOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ оплаты.
        /// </summary>
        public static string OrderPaymentType {
            get {
                return ResourceManager.GetString("OrderPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказов.
        /// </summary>
        public static string OrdersAmount {
            get {
                return ResourceManager.GetString("OrdersAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество заказов.
        /// </summary>
        public static string OrdersCount {
            get {
                return ResourceManager.GetString("OrdersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во заказов на курьера в час.
        /// </summary>
        public static string OrdersCountOnCouriers {
            get {
                return ResourceManager.GetString("OrdersCountOnCouriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказов доставлено.
        /// </summary>
        public static string OrdersDelivered {
            get {
                return ResourceManager.GetString("OrdersDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказов на курьера в час.
        /// </summary>
        public static string OrdersOnCouriersInHourCount {
            get {
                return ResourceManager.GetString("OrdersOnCouriersInHourCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильн.Прил..
        /// </summary>
        public static string OrderSourceMobile {
            get {
                return ResourceManager.GetString("OrderSourceMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источники заказов.
        /// </summary>
        public static string OrderSources {
            get {
                return ResourceManager.GetString("OrderSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string OrderSourceSite {
            get {
                return ResourceManager.GetString("OrderSourceSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус заказа.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип заказа.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф (Ожидание).
        /// </summary>
        public static string OverdueBonus {
            get {
                return ResourceManager.GetString("OverdueBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упаковка.
        /// </summary>
        public static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упаковка.
        /// </summary>
        public static string PackingTable {
            get {
                return ResourceManager.GetString("PackingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PaymentCardTransId {
            get {
                return ResourceManager.GetString("PaymentCardTransId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питание персонала.
        /// </summary>
        public static string PersonalFood {
            get {
                return ResourceManager.GetString("PersonalFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самовывоз.
        /// </summary>
        public static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пицца.
        /// </summary>
        public static string Pizza {
            get {
                return ResourceManager.GetString("Pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во пицц и закусок на человека в час.
        /// </summary>
        public static string PizzaAndCompositionCountOnEmployee {
            get {
                return ResourceManager.GetString("PizzaAndCompositionCountOnEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во пицц на человека в час.
        /// </summary>
        public static string PizzaCountOnEmployee {
            get {
                return ResourceManager.GetString("PizzaCountOnEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиццерия.
        /// </summary>
        public static string Pizzeria {
            get {
                return ResourceManager.GetString("Pizzeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доля.
        /// </summary>
        public static string Portion {
            get {
                return ResourceManager.GetString("Portion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовление.
        /// </summary>
        public static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время изготовления.
        /// </summary>
        public static string PreparationTime {
            get {
                return ResourceManager.GetString("PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подарок.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории продуктов.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id продукта.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовление.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название продукта.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукты.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи.
        /// </summary>
        public static string ProductSales {
            get {
                return ResourceManager.GetString("ProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа продуктов.
        /// </summary>
        public static string ProductsGroup {
            get {
                return ResourceManager.GetString("ProductsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип продукта.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промокод.
        /// </summary>
        public static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промо-код.
        /// </summary>
        public static string PromoCode {
            get {
                return ResourceManager.GetString("PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штука.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шт..
        /// </summary>
        public static string QuantityShort {
            get {
                return ResourceManager.GetString("QuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина остановки.
        /// </summary>
        public static string ReasonStopSale {
            get {
                return ResourceManager.GetString("ReasonStopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет:.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход продуктов.
        /// </summary>
        public static string ReportName_ConsumptionProducts {
            get {
                return ResourceManager.GetString("ReportName_ConsumptionProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зона доставки.
        /// </summary>
        public static string ReportName_DeliverySectorsReport {
            get {
                return ResourceManager.GetString("ReportName_DeliverySectorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просроченные экспресс-продукты.
        /// </summary>
        public static string ReportName_ExpressProductsStatistics {
            get {
                return ResourceManager.GetString("ReportName_ExpressProductsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруженность курьеров.
        /// </summary>
        public static string ReportName_ProductivityCouriersStatistic {
            get {
                return ResourceManager.GetString("ReportName_ProductivityCouriersStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по продажам продуктов.
        /// </summary>
        public static string ReportName_ProductsSalesForCalculationCard {
            get {
                return ResourceManager.GetString("ReportName_ProductsSalesForCalculationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивация кухни.
        /// </summary>
        public static string ReportName_ReportKitchenMotivation {
            get {
                return ResourceManager.GetString("ReportName_ReportKitchenMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выручка.
        /// </summary>
        public static string ReportName_Revenue {
            get {
                return ResourceManager.GetString("ReportName_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остальное.
        /// </summary>
        public static string RestOfDeliverySectors {
            get {
                return ResourceManager.GetString("RestOfDeliverySectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выручка.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выручка на человека в час.
        /// </summary>
        public static string RevenueOnEmployee {
            get {
                return ResourceManager.GetString("RevenueOnEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип ревизии.
        /// </summary>
        public static string RevisionType {
            get {
                return ResourceManager.GetString("RevisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ревизор:.
        /// </summary>
        public static string Revisor {
            get {
                return ResourceManager.GetString("Revisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string SalaryCategory {
            get {
                return ResourceManager.GetString("SalaryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневные часы.
        /// </summary>
        public static string SalaryDayHours {
            get {
                return ResourceManager.GetString("SalaryDayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗП, день.
        /// </summary>
        public static string SalaryDayMoney {
            get {
                return ResourceManager.GetString("SalaryDayMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия, имя.
        /// </summary>
        public static string SalaryEmployeeName {
            get {
                return ResourceManager.GetString("SalaryEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэф-т особого дня.
        /// </summary>
        public static string SalaryHolidayFactor {
            get {
                return ResourceManager.GetString("SalaryHolidayFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праздничные часы.
        /// </summary>
        public static string SalaryHolidayHours {
            get {
                return ResourceManager.GetString("SalaryHolidayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата кухни.
        /// </summary>
        public static string SalaryKitchenStaff {
            get {
                return ResourceManager.GetString("SalaryKitchenStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночной коэф-т.
        /// </summary>
        public static string SalaryNightFactor {
            get {
                return ResourceManager.GetString("SalaryNightFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночные часы.
        /// </summary>
        public static string SalaryNightHours {
            get {
                return ResourceManager.GetString("SalaryNightHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗП, ночь.
        /// </summary>
        public static string SalaryNightMoney {
            get {
                return ResourceManager.GetString("SalaryNightMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗП, премия.
        /// </summary>
        public static string SalaryPremiumMoney {
            get {
                return ResourceManager.GetString("SalaryPremiumMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставка.
        /// </summary>
        public static string SalaryRate {
            get {
                return ResourceManager.GetString("SalaryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания смены.
        /// </summary>
        public static string SalaryShiftEndDate {
            get {
                return ResourceManager.GetString("SalaryShiftEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания смены.
        /// </summary>
        public static string SalaryShiftEndTime {
            get {
                return ResourceManager.GetString("SalaryShiftEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания смены.
        /// </summary>
        public static string SalaryShiftStartDate {
            get {
                return ResourceManager.GetString("SalaryShiftStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала смены.
        /// </summary>
        public static string SalaryShiftStartTime {
            get {
                return ResourceManager.GetString("SalaryShiftStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время смены.
        /// </summary>
        public static string SalaryShiftTime {
            get {
                return ResourceManager.GetString("SalaryShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего часов.
        /// </summary>
        public static string SalaryTotalHours {
            get {
                return ResourceManager.GetString("SalaryTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        public static string SalaryTotalMoney {
            get {
                return ResourceManager.GetString("SalaryTotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид продажи.
        /// </summary>
        public static string SalesType {
            get {
                return ResourceManager.GetString("SalesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время продажи (печати чека).
        /// </summary>
        public static string SaleTime {
            get {
                return ResourceManager.GetString("SaleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление продажи.
        /// </summary>
        public static string SaleType {
            get {
                return ResourceManager.GetString("SaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Субботы.
        /// </summary>
        public static string Saturdays {
            get {
                return ResourceManager.GetString("Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Выберите класс сырья -.
        /// </summary>
        public static string SelectInventoryType {
            get {
                return ResourceManager.GetString("SelectInventoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Выберите единицу измерения -.
        /// </summary>
        public static string SelectUnitsOfMeasure {
            get {
                return ResourceManager.GetString("SelectUnitsOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полуфабрикат.
        /// </summary>
        public static string SemiFinishedProduct {
            get {
                return ResourceManager.GetString("SemiFinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер смены.
        /// </summary>
        public static string ShiftNumber {
            get {
                return ResourceManager.GetString("ShiftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утренняя смена,Вечерняя смена,Ночная смена.
        /// </summary>
        public static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип смены.
        /// </summary>
        public static string ShiftType {
            get {
                return ResourceManager.GetString("ShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартный.
        /// </summary>
        public static string SliderType_Default {
            get {
                return ResourceManager.GetString("SliderType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для кусочков.
        /// </summary>
        public static string SliderType_ForPieces {
            get {
                return ResourceManager.GetString("SliderType_ForPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - ваш код для списания додо-рублей..
        /// </summary>
        public static string SmsWithCodeWord {
            get {
                return ResourceManager.GetString("SmsWithCodeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не для всех выбранных продуктов указана цена..
        /// </summary>
        public static string SomeProductsHaveNoPrice {
            get {
                return ResourceManager.GetString("SomeProductsHaveNoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальная цена.
        /// </summary>
        public static string SpecialPrice {
            get {
                return ResourceManager.GetString("SpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторан.
        /// </summary>
        public static string Stationary {
            get {
                return ResourceManager.GetString("Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка продаж.
        /// </summary>
        public static string StopSale {
            get {
                return ResourceManager.GetString("StopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина строки для поля {0} не может быть больше {1} символов.
        /// </summary>
        public static string StringLengthExeedsMaximum {
            get {
                return ResourceManager.GetString("StringLengthExeedsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресения.
        /// </summary>
        public static string Sundays {
            get {
                return ResourceManager.GetString("Sundays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табельный номер.
        /// </summary>
        public static string TabNo {
            get {
                return ResourceManager.GetString("TabNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типовое описание.
        /// </summary>
        public static string TechnicalDescription {
            get {
                return ResourceManager.GetString("TechnicalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четверги.
        /// </summary>
        public static string Thursdays {
            get {
                return ResourceManager.GetString("Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % просрочки.
        /// </summary>
        public static string TimeOutOrdersPercentage {
            get {
                return ResourceManager.GetString("TimeOutOrdersPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание.
        /// </summary>
        public static string TimeOutPeriod {
            get {
                return ResourceManager.GetString("TimeOutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала смены.
        /// </summary>
        public static string TimeReportBeginDateColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportBeginDateColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала смены.
        /// </summary>
        public static string TimeReportBeginTimeColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportBeginTimeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string TimeReportCategoryColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportCategoryColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневные часы.
        /// </summary>
        public static string TimeReportDayHoursColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportDayHoursColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия, имя сотрудника.
        /// </summary>
        public static string TimeReportEmployeeColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportEmployeeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания смены.
        /// </summary>
        public static string TimeReportEndDateColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportEndDateColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания смены.
        /// </summary>
        public static string TimeReportEndTimeColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportEndTimeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        public static string TimeReportHoursTotalColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportHoursTotalColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночные часы.
        /// </summary>
        public static string TimeReportNightHoursColumnTitle {
            get {
                return ResourceManager.GetString("TimeReportNightHoursColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность секторов доставки.
        /// </summary>
        public static string Title_ActivityDeliverySectors {
            get {
                return ResourceManager.GetString("Title_ActivityDeliverySectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность по акциям.
        /// </summary>
        public static string Title_BonusActionActivityReport {
            get {
                return ResourceManager.GetString("Title_BonusActionActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применение автоматических акций.
        /// </summary>
        public static string Title_BonusActionsReport {
            get {
                return ResourceManager.GetString("Title_BonusActionsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по клиентам.
        /// </summary>
        public static string Title_ClientsStatisicReport {
            get {
                return ResourceManager.GetString("Title_ClientsStatisicReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по курьерам.
        /// </summary>
        public static string Title_CourierStatisicReport {
            get {
                return ResourceManager.GetString("Title_CourierStatisicReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поездки курьеров.
        /// </summary>
        public static string Title_CourierTasks {
            get {
                return ResourceManager.GetString("Title_CourierTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забракованные продукты.
        /// </summary>
        public static string Title_DefectiveProductsReport {
            get {
                return ResourceManager.GetString("Title_DefectiveProductsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по доставке.
        /// </summary>
        public static string Title_DeliveryStatistic {
            get {
                return ResourceManager.GetString("Title_DeliveryStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход теста.
        /// </summary>
        public static string Title_DoughReport {
            get {
                return ResourceManager.GetString("Title_DoughReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Cost.
        /// </summary>
        public static string Title_LabourCost {
            get {
                return ResourceManager.GetString("Title_LabourCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Title_OrdersReport {
            get {
                return ResourceManager.GetString("Title_OrdersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время изготовления.
        /// </summary>
        public static string Title_ProductionTimeReport {
            get {
                return ResourceManager.GetString("Title_ProductionTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по загруженности.
        /// </summary>
        public static string Title_ReportPizzeriaLoad {
            get {
                return ResourceManager.GetString("Title_ReportPizzeriaLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Title_ReportPizzeriaLoadOrders {
            get {
                return ResourceManager.GetString("Title_ReportPizzeriaLoadOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукты.
        /// </summary>
        public static string Title_ReportPizzeriaLoadProducts {
            get {
                return ResourceManager.GetString("Title_ReportPizzeriaLoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярность продуктов.
        /// </summary>
        public static string Title_ReportPopularityProducts {
            get {
                return ResourceManager.GetString("Title_ReportPopularityProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производительность.
        /// </summary>
        public static string Title_ReportProductivity {
            get {
                return ResourceManager.GetString("Title_ReportProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход промо-кодов.
        /// </summary>
        public static string Title_ReportPromoCodeUsed {
            get {
                return ResourceManager.GetString("Title_ReportPromoCodeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи по кассовым сменам.
        /// </summary>
        public static string Title_ReportSaleByCashBoxSessions {
            get {
                return ResourceManager.GetString("Title_ReportSaleByCashBoxSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доля выручки, %.
        /// </summary>
        public static string Title_RevenuePercentage {
            get {
                return ResourceManager.GetString("Title_RevenuePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата.
        /// </summary>
        public static string Title_SalaryReport {
            get {
                return ResourceManager.GetString("Title_SalaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продано, шт.
        /// </summary>
        public static string Title_SaleCount {
            get {
                return ResourceManager.GetString("Title_SaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп-продажи.
        /// </summary>
        public static string Title_StopSaleReport {
            get {
                return ResourceManager.GetString("Title_StopSaleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое время.
        /// </summary>
        public static string Title_TimeReport {
            get {
                return ResourceManager.GetString("Title_TimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма НДС.
        /// </summary>
        public static string TotalNDS {
            get {
                return ResourceManager.GetString("TotalNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказов по акции.
        /// </summary>
        public static string TotalOrdersPrice {
            get {
                return ResourceManager.GetString("TotalOrdersPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого к выплате за период.
        /// </summary>
        public static string TotalPayableForPeriod {
            get {
                return ResourceManager.GetString("TotalPayableForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторники.
        /// </summary>
        public static string Tuesdays {
            get {
                return ResourceManager.GetString("Tuesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string Unitate {
            get {
                return ResourceManager.GetString("Unitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string UnitateName {
            get {
                return ResourceManager.GetString("UnitateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдел.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделы:.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто возобновил.
        /// </summary>
        public static string UserBeginSale {
            get {
                return ResourceManager.GetString("UserBeginSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто остановил.
        /// </summary>
        public static string UserStopSale {
            get {
                return ResourceManager.GetString("UserStopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество применений.
        /// </summary>
        public static string UsingCount {
            get {
                return ResourceManager.GetString("UsingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнены дни недели.
        /// </summary>
        public static string ValidationRequiredMockupDaysOfWeek {
            get {
                return ResourceManager.GetString("ValidationRequiredMockupDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано название макета.
        /// </summary>
        public static string ValidationRequiredMockupName {
            get {
                return ResourceManager.GetString("ValidationRequiredMockupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание.
        /// </summary>
        public static string WaitingTime {
            get {
                return ResourceManager.GetString("WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среды.
        /// </summary>
        public static string Wednesdays {
            get {
                return ResourceManager.GetString("Wednesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выходные.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруженность.
        /// </summary>
        public static string WorkLoad {
            get {
                return ResourceManager.GetString("WorkLoad", resourceCulture);
            }
        }
    }
}
