//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.StopList {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.StopList.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить объект из стоп-листа.
        /// </summary>
        public static string Error_CanNotRemoveItem {
            get {
                return ResourceManager.GetString("Error_CanNotRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица уже добавлена в стоп-лист.
        /// </summary>
        public static string Error_DeliveryUnitIsInStop {
            get {
                return ResourceManager.GetString("Error_DeliveryUnitIsInStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор уже добавлен в стоп-лист.
        /// </summary>
        public static string Error_SectorIsInStop {
            get {
                return ResourceManager.GetString("Error_SectorIsInStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ингредиент.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печь.
        /// </summary>
        public static string Oven {
            get {
                return ResourceManager.GetString("Oven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистка печи.
        /// </summary>
        public static string OvenCleaning {
            get {
                return ResourceManager.GetString("OvenCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема с интернетом.
        /// </summary>
        public static string StopListReason_InternetProblems {
            get {
                return ResourceManager.GetString("StopListReason_InternetProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нехватка курьеров.
        /// </summary>
        public static string StopListReason_LackOfCouriers {
            get {
                return ResourceManager.GetString("StopListReason_LackOfCouriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нехватка сотрудников на кухне.
        /// </summary>
        public static string StopListReason_LackOfKitchenWorkers {
            get {
                return ResourceManager.GetString("StopListReason_LackOfKitchenWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонт в пиццерии.
        /// </summary>
        public static string StopListReason_PizzeriaRepairment {
            get {
                return ResourceManager.GetString("StopListReason_PizzeriaRepairment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключение электричества/воды/газа.
        /// </summary>
        public static string StopListReason_PowerOutage {
            get {
                return ResourceManager.GetString("StopListReason_PowerOutage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поломка техники/оборудования.
        /// </summary>
        public static string StopListReason_TechnicalIssues {
            get {
                return ResourceManager.GetString("StopListReason_TechnicalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка продаж.
        /// </summary>
        public static string StopSale {
            get {
                return ResourceManager.GetString("StopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
    }
}
