//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Common {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Common.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осень.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тонкое.
        /// </summary>
        public static string DoughThin {
            get {
                return ResourceManager.GetString("DoughThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Традиционное.
        /// </summary>
        public static string DoughTraditional {
            get {
                return ResourceManager.GetString("DoughTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно введены данные.
        /// </summary>
        public static string Error_IncorrectInputString {
            get {
                return ResourceManager.GetString("Error_IncorrectInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятница.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятницы.
        /// </summary>
        public static string Fridays {
            get {
                return ResourceManager.GetString("Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пт..
        /// </summary>
        public static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ж.
        /// </summary>
        public static string Gender_Female_Short {
            get {
                return ResourceManager.GetString("Gender_Female_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to М.
        /// </summary>
        public static string Gender_Male_Short {
            get {
                return ResourceManager.GetString("Gender_Male_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано.
        /// </summary>
        public static string Gender_Unknown {
            get {
                return ResourceManager.GetString("Gender_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понедельник.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понедельники.
        /// </summary>
        public static string Mondays {
            get {
                return ResourceManager.GetString("Mondays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн..
        /// </summary>
        public static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большая.
        /// </summary>
        public static string PizzaLarge {
            get {
                return ResourceManager.GetString("PizzaLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя.
        /// </summary>
        public static string PizzaMedium {
            get {
                return ResourceManager.GetString("PizzaMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартная.
        /// </summary>
        public static string PizzaStandard {
            get {
                return ResourceManager.GetString("PizzaStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не задано.
        /// </summary>
        public static string PizzaUndefined {
            get {
                return ResourceManager.GetString("PizzaUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суббота.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Субботы.
        /// </summary>
        public static string Saturdays {
            get {
                return ResourceManager.GetString("Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сб..
        /// </summary>
        public static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Весна.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лето.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресенье.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресения.
        /// </summary>
        public static string Sundays {
            get {
                return ResourceManager.GetString("Sundays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вс..
        /// </summary>
        public static string SundayShort {
            get {
                return ResourceManager.GetString("SundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четверг.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четверги.
        /// </summary>
        public static string Thursdays {
            get {
                return ResourceManager.GetString("Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чт..
        /// </summary>
        public static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторники.
        /// </summary>
        public static string Tuesdays {
            get {
                return ResourceManager.GetString("Tuesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вт..
        /// </summary>
        public static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допускаются только латинские буквы,цифры и символы: &apos;-&apos;, &apos;_&apos;, &apos;.&apos;.
        /// </summary>
        public static string ValidateMesage_OnlyLettersDigitsSpecialCharacters {
            get {
                return ResourceManager.GetString("ValidateMesage_OnlyLettersDigitsSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя ввести два одинаковых значения.
        /// </summary>
        public static string ValidateMessage_NotEqualTwoFields {
            get {
                return ResourceManager.GetString("ValidateMessage_NotEqualTwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среда.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среды.
        /// </summary>
        public static string Wednesdays {
            get {
                return ResourceManager.GetString("Wednesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ср..
        /// </summary>
        public static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зима.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
