//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Finance {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Currency {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currency() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Finance.Currency", typeof(Currency).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string EuroShort {
            get {
                return ResourceManager.GetString("EuroShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн..
        /// </summary>
        internal static string Hryvnia {
            get {
                return ResourceManager.GetString("Hryvnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн..
        /// </summary>
        internal static string HryvniaShort {
            get {
                return ResourceManager.GetString("HryvniaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        internal static string PoundSterling {
            get {
                return ResourceManager.GetString("PoundSterling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        internal static string PoundSterlingShort {
            get {
                return ResourceManager.GetString("PoundSterlingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lei.
        /// </summary>
        internal static string RomanianLeu {
            get {
                return ResourceManager.GetString("RomanianLeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string RomanianLeuShort {
            get {
                return ResourceManager.GetString("RomanianLeuShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to руб..
        /// </summary>
        internal static string RussianRuble {
            get {
                return ResourceManager.GetString("RussianRuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р..
        /// </summary>
        internal static string RussianRubleShort {
            get {
                return ResourceManager.GetString("RussianRubleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сом.
        /// </summary>
        internal static string Som {
            get {
                return ResourceManager.GetString("Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сом.
        /// </summary>
        internal static string SomShort {
            get {
                return ResourceManager.GetString("SomShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тенге.
        /// </summary>
        internal static string Tenge {
            get {
                return ResourceManager.GetString("Tenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тг..
        /// </summary>
        internal static string TengeShort {
            get {
                return ResourceManager.GetString("TengeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to руб..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р..
        /// </summary>
        internal static string UnknownShort {
            get {
                return ResourceManager.GetString("UnknownShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string USDollar {
            get {
                return ResourceManager.GetString("USDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string USDollarShort {
            get {
                return ResourceManager.GetString("USDollarShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        internal static string UzbekistanSum {
            get {
                return ResourceManager.GetString("UzbekistanSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        internal static string UzbekistanSumShort {
            get {
                return ResourceManager.GetString("UzbekistanSumShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        internal static string YuanRenminbi {
            get {
                return ResourceManager.GetString("YuanRenminbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        internal static string YuanRenminbiShort {
            get {
                return ResourceManager.GetString("YuanRenminbiShort", resourceCulture);
            }
        }
    }
}
