//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Finance {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Finance.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付宝支付.
        /// </summary>
        public static string AcquiringTypeAliPay {
            get {
                return ResourceManager.GetString("AcquiringTypeAliPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БРС.
        /// </summary>
        public static string AcquiringTypeBRS {
            get {
                return ResourceManager.GetString("AcquiringTypeBRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodo gateway.
        /// </summary>
        public static string AcquiringTypeDodoPay {
            get {
                return ResourceManager.GetString("AcquiringTypeDodoPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EuPlatesc.
        /// </summary>
        public static string AcquiringTypeEuPlatesc {
            get {
                return ResourceManager.GetString("AcquiringTypeEuPlatesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestpay.
        /// </summary>
        public static string AcquiringTypeNestpay {
            get {
                return ResourceManager.GetString("AcquiringTypeNestpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEB (Эстония).
        /// </summary>
        public static string AcquiringTypeSEBEe {
            get {
                return ResourceManager.GetString("AcquiringTypeSEBEe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEB.
        /// </summary>
        public static string AcquiringTypeSEBEeShort {
            get {
                return ResourceManager.GetString("AcquiringTypeSEBEeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEB (Литва).
        /// </summary>
        public static string AcquiringTypeSEBLithuania {
            get {
                return ResourceManager.GetString("AcquiringTypeSEBLithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEB.
        /// </summary>
        public static string AcquiringTypeSEBLithuaniaShort {
            get {
                return ResourceManager.GetString("AcquiringTypeSEBLithuaniaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartland SecureSubmit.
        /// </summary>
        public static string AcquiringTypeSecureSubmit {
            get {
                return ResourceManager.GetString("AcquiringTypeSecureSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe.
        /// </summary>
        public static string AcquiringTypeStripe {
            get {
                return ResourceManager.GetString("AcquiringTypeStripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedbank (Эстония).
        /// </summary>
        public static string AcquiringTypeSwedbankEe {
            get {
                return ResourceManager.GetString("AcquiringTypeSwedbankEe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedbank.
        /// </summary>
        public static string AcquiringTypeSwedbankEeShort {
            get {
                return ResourceManager.GetString("AcquiringTypeSwedbankEeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedbank (Литва).
        /// </summary>
        public static string AcquiringTypeSwedbankLt {
            get {
                return ResourceManager.GetString("AcquiringTypeSwedbankLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedbank.
        /// </summary>
        public static string AcquiringTypeSwedbankLtShort {
            get {
                return ResourceManager.GetString("AcquiringTypeSwedbankLtShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wechat.
        /// </summary>
        public static string AcquiringTypeWechatPay {
            get {
                return ResourceManager.GetString("AcquiringTypeWechatPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.Касса.
        /// </summary>
        public static string AcquiringTypeYandex {
            get {
                return ResourceManager.GetString("AcquiringTypeYandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аура-01ФР-KZ.
        /// </summary>
        public static string CashBoxModel_Aura {
            get {
                return ResourceManager.GetString("CashBoxModel_Aura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтер чеков.
        /// </summary>
        public static string CashBoxModel_ChequePrinter {
            get {
                return ResourceManager.GetString("CashBoxModel_ChequePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen CT-S310II.
        /// </summary>
        public static string CashBoxModel_Citizen {
            get {
                return ResourceManager.GetString("CashBoxModel_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPrint-22/22K.
        /// </summary>
        public static string CashBoxModel_FPrint {
            get {
                return ResourceManager.GetString("CashBoxModel_FPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPrint-22ПТК Online.
        /// </summary>
        public static string CashBoxModel_FPrintOnline {
            get {
                return ResourceManager.GetString("CashBoxModel_FPrintOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штрих-М.
        /// </summary>
        public static string CashBoxModel_Shtrih {
            get {
                return ResourceManager.GetString("CashBoxModel_Shtrih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XKUBE-F.
        /// </summary>
        public static string CashBoxModel_XKube {
            get {
                return ResourceManager.GetString("CashBoxModel_XKube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Currency_Dollar {
            get {
                return ResourceManager.GetString("Currency_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Currency_Euro {
            get {
                return ResourceManager.GetString("Currency_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн.
        /// </summary>
        public static string Currency_Grivna {
            get {
                return ResourceManager.GetString("Currency_Grivna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string Currency_PoundSterling {
            get {
                return ResourceManager.GetString("Currency_PoundSterling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lei.
        /// </summary>
        public static string Currency_RomanianLeu {
            get {
                return ResourceManager.GetString("Currency_RomanianLeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₽.
        /// </summary>
        public static string Currency_Ruble {
            get {
                return ResourceManager.GetString("Currency_Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сом.
        /// </summary>
        public static string Currency_Som {
            get {
                return ResourceManager.GetString("Currency_Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        public static string Currency_Sum {
            get {
                return ResourceManager.GetString("Currency_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тг..
        /// </summary>
        public static string Currency_Tenge {
            get {
                return ResourceManager.GetString("Currency_Tenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string Currency_Unknown {
            get {
                return ResourceManager.GetString("Currency_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        public static string Currency_Yuan {
            get {
                return ResourceManager.GetString("Currency_Yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Decrease_Dollar {
            get {
                return ResourceManager.GetString("Decrease_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Decrease_Euro {
            get {
                return ResourceManager.GetString("Decrease_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн.
        /// </summary>
        public static string Decrease_Grivna {
            get {
                return ResourceManager.GetString("Decrease_Grivna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string Decrease_PoundSterling {
            get {
                return ResourceManager.GetString("Decrease_PoundSterling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lei.
        /// </summary>
        public static string Decrease_RomanianLeu {
            get {
                return ResourceManager.GetString("Decrease_RomanianLeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р..
        /// </summary>
        public static string Decrease_Ruble {
            get {
                return ResourceManager.GetString("Decrease_Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сом.
        /// </summary>
        public static string Decrease_Som {
            get {
                return ResourceManager.GetString("Decrease_Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        public static string Decrease_Sum {
            get {
                return ResourceManager.GetString("Decrease_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тг..
        /// </summary>
        public static string Decrease_Tenge {
            get {
                return ResourceManager.GetString("Decrease_Tenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string Decrease_Unknown {
            get {
                return ResourceManager.GetString("Decrease_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        public static string Decrease_Yuan {
            get {
                return ResourceManager.GetString("Decrease_Yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dollar_Decrease {
            get {
                return ResourceManager.GetString("Dollar_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Euro_Decrease {
            get {
                return ResourceManager.GetString("Euro_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доллар.
        /// </summary>
        public static string Name_Dollar {
            get {
                return ResourceManager.GetString("Name_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Евро.
        /// </summary>
        public static string Name_Euro {
            get {
                return ResourceManager.GetString("Name_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гривна.
        /// </summary>
        public static string Name_Grivna {
            get {
                return ResourceManager.GetString("Name_Grivna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фунт стерлингов.
        /// </summary>
        public static string Name_PoundSterling {
            get {
                return ResourceManager.GetString("Name_PoundSterling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лей.
        /// </summary>
        public static string Name_RomanianLeu {
            get {
                return ResourceManager.GetString("Name_RomanianLeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рубль.
        /// </summary>
        public static string Name_Ruble {
            get {
                return ResourceManager.GetString("Name_Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сом.
        /// </summary>
        public static string Name_Som {
            get {
                return ResourceManager.GetString("Name_Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сум.
        /// </summary>
        public static string Name_Sum {
            get {
                return ResourceManager.GetString("Name_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тенге.
        /// </summary>
        public static string Name_Tenge {
            get {
                return ResourceManager.GetString("Name_Tenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неопределено.
        /// </summary>
        public static string Name_Unknown {
            get {
                return ResourceManager.GetString("Name_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юань.
        /// </summary>
        public static string Name_Yuan {
            get {
                return ResourceManager.GetString("Name_Yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NeedToLogin {
            get {
                return ResourceManager.GetString("NeedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта (агрегатор).
        /// </summary>
        public static string PaymentType_Aggregator {
            get {
                return ResourceManager.GetString("PaymentType_Aggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string PaymentType_Card {
            get {
                return ResourceManager.GetString("PaymentType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные.
        /// </summary>
        public static string PaymentType_Cash {
            get {
                return ResourceManager.GetString("PaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта(сайт).
        /// </summary>
        public static string PaymentType_InternetAcquiring {
            get {
                return ResourceManager.GetString("PaymentType_InternetAcquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ruble_Decrease {
            get {
                return ResourceManager.GetString("Ruble_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налог с продаж.
        /// </summary>
        public static string TaxType_SaleTax {
            get {
                return ResourceManager.GetString("TaxType_SaleTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано.
        /// </summary>
        public static string TaxType_Unknown {
            get {
                return ResourceManager.GetString("TaxType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НДС.
        /// </summary>
        public static string TaxType_Vat {
            get {
                return ResourceManager.GetString("TaxType_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НДС по направлению продаж.
        /// </summary>
        public static string TaxType_VatTowardsSales {
            get {
                return ResourceManager.GetString("TaxType_VatTowardsSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Title_AccessDenied {
            get {
                return ResourceManager.GetString("Title_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to версия 4139 и ниже.
        /// </summary>
        public static string CashBoxSoftwareIdentifierVersion_FPrintOnline_4139 {
            get {
                return ResourceManager.GetString("CashBoxSoftwareIdentifierVersion_FPrintOnline_4139", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to версия 4555 и выше.
        /// </summary>
        public static string CashBoxSoftwareIdentifierVersion_FPrintOnline_4555 {
            get {
                return ResourceManager.GetString("CashBoxSoftwareIdentifierVersion_FPrintOnline_4555", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не выбрана.
        /// </summary>
        public static string CashBoxSoftwareIdentifierVersion_None {
            get {
                return ResourceManager.GetString("CashBoxSoftwareIdentifierVersion_None", resourceCulture);
            }
        }
    }
}
