//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Products.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная.
        /// </summary>
        public static string AdditionalSaleTypeActive {
            get {
                return ResourceManager.GetString("AdditionalSaleTypeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная (всплывающее окно).
        /// </summary>
        public static string AdditionalSaleTypeActiveTitle {
            get {
                return ResourceManager.GetString("AdditionalSaleTypeActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассивная.
        /// </summary>
        public static string AdditionalSaleTypePassive {
            get {
                return ResourceManager.GetString("AdditionalSaleTypePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассивная (в блоке на странице корзины).
        /// </summary>
        public static string AdditionalSaleTypePassiveTitle {
            get {
                return ResourceManager.GetString("AdditionalSaleTypePassiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приготовление заранее.
        /// </summary>
        public static string AdvancePreparationScheme {
            get {
                return ResourceManager.GetString("AdvancePreparationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все дни.
        /// </summary>
        public static string AllDays {
            get {
                return ResourceManager.GetString("AllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматический.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большие пиццы.
        /// </summary>
        public static string BigPizzas {
            get {
                return ResourceManager.GetString("BigPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приготовление в кассовой зоне.
        /// </summary>
        public static string CashZonePreparationScheme {
            get {
                return ResourceManager.GetString("CashZonePreparationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Десерты.
        /// </summary>
        public static string CategoryDesserts {
            get {
                return ResourceManager.GetString("CategoryDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напитки.
        /// </summary>
        public static string CategoryDrinks {
            get {
                return ResourceManager.GetString("CategoryDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string CategoryGoods {
            get {
                return ResourceManager.GetString("CategoryGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кусочки.
        /// </summary>
        public static string CategoryPieces {
            get {
                return ResourceManager.GetString("CategoryPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пицца.
        /// </summary>
        public static string CategoryPizza {
            get {
                return ResourceManager.GetString("CategoryPizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соусы.
        /// </summary>
        public static string CategorySauces {
            get {
                return ResourceManager.GetString("CategorySauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закуски.
        /// </summary>
        public static string CategorySnacks {
            get {
                return ResourceManager.GetString("CategorySnacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комбо.
        /// </summary>
        public static string Combo {
            get {
                return ResourceManager.GetString("Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голубой (сгущенка).
        /// </summary>
        public static string Constructor_SauceColorBase_Blue {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темно серый (ранч).
        /// </summary>
        public static string Constructor_SauceColorBase_DarkGray {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зеленый (карри).
        /// </summary>
        public static string Constructor_SauceColorBase_Green {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиолетовый (чесночный).
        /// </summary>
        public static string Constructor_SauceColorBase_Purple {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красный (томатный).
        /// </summary>
        public static string Constructor_SauceColorBase_Red {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белый (Альфредо).
        /// </summary>
        public static string Constructor_SauceColorBase_White {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желтый (сырный).
        /// </summary>
        public static string Constructor_SauceColorBase_Yellow {
            get {
                return ResourceManager.GetString("Constructor_SauceColorBase_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без соуса.
        /// </summary>
        public static string Constructor_SauceUnknown {
            get {
                return ResourceManager.GetString("Constructor_SauceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка и ресторан.
        /// </summary>
        public static string DeliveryAndStationary {
            get {
                return ResourceManager.GetString("DeliveryAndStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню доставки.
        /// </summary>
        public static string DeliveryMenu {
            get {
                return ResourceManager.GetString("DeliveryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется отправка.
        /// </summary>
        public static string DistributionStatusSending {
            get {
                return ResourceManager.GetString("DistributionStatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание.
        /// </summary>
        public static string DistributionStatusWaiting {
            get {
                return ResourceManager.GetString("DistributionStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        public static string DistributionStatusСompleted {
            get {
                return ResourceManager.GetString("DistributionStatusСompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана размерная характеристика.
        /// </summary>
        public static string Error_EmptyDimensionalCharacteristics {
            get {
                return ResourceManager.GetString("Error_EmptyDimensionalCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная цена. Должна быть кратна {0}..
        /// </summary>
        public static string Error_IncorrectPriceInHundred {
            get {
                return ResourceManager.GetString("Error_IncorrectPriceInHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная цена. Должна быть кратна 1..
        /// </summary>
        public static string Error_IncorrectPriceInOneNumber {
            get {
                return ResourceManager.GetString("Error_IncorrectPriceInOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное количество.
        /// </summary>
        public static string Error_Number {
            get {
                return ResourceManager.GetString("Error_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания продаж не может быть меньше даты начала.
        /// </summary>
        public static string Error_SalePeriod_EndDateLessThanStartDate {
            get {
                return ResourceManager.GetString("Error_SalePeriod_EndDateLessThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя задать дату начала продаж в прошлом.
        /// </summary>
        public static string Error_SalePeriod_StartDateCannotBeInThePast {
            get {
                return ResourceManager.GetString("Error_SalePeriod_StartDateCannotBeInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно поменять только будущую дату начала продаж.
        /// </summary>
        public static string Error_SalePeriod_StartDateCannotChange {
            get {
                return ResourceManager.GetString("Error_SalePeriod_StartDateCannotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное название размерной характеристики.
        /// </summary>
        public static string Error_TooLongDimensionalCharacteristics {
            get {
                return ResourceManager.GetString("Error_TooLongDimensionalCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Цена со скидкой&quot; должно содержать не более 10 символов.
        /// </summary>
        public static string ErrorMessage_DiscountPriceValueLengthMax10Сharacter {
            get {
                return ResourceManager.GetString("ErrorMessage_DiscountPriceValueLengthMax10Сharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMessage_InvalidClientId {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMessage_NotEnoughMoney {
            get {
                return ResourceManager.GetString("ErrorMessage_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена не может быть меньше 0.
        /// </summary>
        public static string ErrorMessage_PriceMustBePositive {
            get {
                return ResourceManager.GetString("ErrorMessage_PriceMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Цена&quot; содержит недопустимое значение.
        /// </summary>
        public static string ErrorMessage_PriceValueHasInvalidValue {
            get {
                return ResourceManager.GetString("ErrorMessage_PriceValueHasInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Цена&quot; должно содержать не более 10 символов.
        /// </summary>
        public static string ErrorMessage_PriceValueLengthMax10Сharacter {
            get {
                return ResourceManager.GetString("ErrorMessage_PriceValueLengthMax10Сharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Цена&quot; должно быть заполнено.
        /// </summary>
        public static string ErrorMessage_PriceValueRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_PriceValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMessage_TransactionNotFond {
            get {
                return ResourceManager.GetString("ErrorMessage_TransactionNotFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Европейское.
        /// </summary>
        public static string European {
            get {
                return ResourceManager.GetString("European", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа ({0}) меньше потраченных додолларов ({1})..
        /// </summary>
        public static string ExceptionMessageTemplateApplyDodollars {
            get {
                return ResourceManager.GetString("ExceptionMessageTemplateApplyDodollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пищевой.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&amp;nbsp;&amp;mdash;&amp;nbsp;{1}.
        /// </summary>
        public static string GoodsSalePeriod {
            get {
                return ResourceManager.GetString("GoodsSalePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендации.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Халяльное.
        /// </summary>
        public static string Halal {
            get {
                return ResourceManager.GetString("Halal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полухаляльное.
        /// </summary>
        public static string HalfHalal {
            get {
                return ResourceManager.GetString("HalfHalal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивный.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ингредиенты.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средние пиццы.
        /// </summary>
        public static string MediumPizzas {
            get {
                return ResourceManager.GetString("MediumPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string MenuAccessibility_Delivery {
            get {
                return ResourceManager.GetString("MenuAccessibility_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питание персонала.
        /// </summary>
        public static string MenuAccessibility_Personal {
            get {
                return ResourceManager.GetString("MenuAccessibility_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторан.
        /// </summary>
        public static string MenuAccessibility_Stationary {
            get {
                return ResourceManager.GetString("MenuAccessibility_Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недействительный промокод.
        /// </summary>
        public static string Message_InvalidPromoCode {
            get {
                return ResourceManager.GetString("Message_InvalidPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to метапродукт.
        /// </summary>
        public static string MetaProduct {
            get {
                return ResourceManager.GetString("MetaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to января,февраля,марта,апреля,мая,июня,июля,августа,сентября,октября,ноября,декабря.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to непищевой.
        /// </summary>
        public static string Nonfood {
            get {
                return ResourceManager.GetString("Nonfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только выходные.
        /// </summary>
        public static string OnlyWeekDays {
            get {
                return ResourceManager.GetString("OnlyWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только будни.
        /// </summary>
        public static string OnlyWorkDays {
            get {
                return ResourceManager.GetString("OnlyWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фасовка.
        /// </summary>
        public static string PackagingScheme {
            get {
                return ResourceManager.GetString("PackagingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню для персонала.
        /// </summary>
        public static string PersonalMenu {
            get {
                return ResourceManager.GetString("PersonalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема для пицц.
        /// </summary>
        public static string PizzaScheme {
            get {
                return ResourceManager.GetString("PizzaScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подарок.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокий.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Низкий.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to продукт.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to круглосут..
        /// </summary>
        public static string ProductMenuSalesTimeArroundClock {
            get {
                return ResourceManager.GetString("ProductMenuSalesTimeArroundClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промокод.
        /// </summary>
        public static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню ресторана.
        /// </summary>
        public static string RestaurantMenu {
            get {
                return ResourceManager.GetString("RestaurantMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отсутствует.
        /// </summary>
        public static string SalePeriodEmpty {
            get {
                return ResourceManager.GetString("SalePeriodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема для сэндвичей.
        /// </summary>
        public static string SandwichScheme {
            get {
                return ResourceManager.GetString("SandwichScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема без производства.
        /// </summary>
        public static string SimpleScheme {
            get {
                return ResourceManager.GetString("SimpleScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маленькие пиццы.
        /// </summary>
        public static string SmallPizzas {
            get {
                return ResourceManager.GetString("SmallPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема для закусок.
        /// </summary>
        public static string SnacksScheme {
            get {
                return ResourceManager.GetString("SnacksScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закуски без выпекания.
        /// </summary>
        public static string SnacksWithoutOvenScheme {
            get {
                return ResourceManager.GetString("SnacksWithoutOvenScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не для всех выбранных продуктов указана цена..
        /// </summary>
        public static string SomeProductsHaveNoPrice {
            get {
                return ResourceManager.GetString("SomeProductsHaveNoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторан.
        /// </summary>
        public static string Stationary {
            get {
                return ResourceManager.GetString("Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string ThinDoughAlias {
            get {
                return ResourceManager.GetString("ThinDoughAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выпечка.
        /// </summary>
        public static string TypeBaked {
            get {
                return ResourceManager.GetString("TypeBaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Составной.
        /// </summary>
        public static string TypeComposite {
            get {
                return ResourceManager.GetString("TypeComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой.
        /// </summary>
        public static string TypeSimple {
            get {
                return ResourceManager.GetString("TypeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без особенностей.
        /// </summary>
        public static string WithoutSpecialization {
            get {
                return ResourceManager.GetString("WithoutSpecialization", resourceCulture);
            }
        }
    }
}
