//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.GlobalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy HH:mm.
        /// </summary>
        public static string DateTimeToStringFormat {
            get {
                return ResourceManager.GetString("DateTimeToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy HH:mm:ss.
        /// </summary>
        public static string DateTimeToStringFullFormat {
            get {
                return ResourceManager.GetString("DateTimeToStringFullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        public static string DateToStringFormat {
            get {
                return ResourceManager.GetString("DateToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-валют|додо-валюта|додо-валюты.
        /// </summary>
        public static string DodoAccusativeFormsDef {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-доллар|додо-доллара|додо-долларов.
        /// </summary>
        public static string DodoAccusativeFormsDollars {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsDollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-евро.
        /// </summary>
        public static string DodoAccusativeFormsEuro {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-гривна|додо-гривны|додо-гривен.
        /// </summary>
        public static string DodoAccusativeFormsGrivna {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsGrivna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-лей.
        /// </summary>
        public static string DodoAccusativeFormsLei {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsLei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-фунт|додо-фунта|додо-фунтов.
        /// </summary>
        public static string DodoAccusativeFormsPoundSterling {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsPoundSterling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-рубль|додо-рубля|додо-рублей.
        /// </summary>
        public static string DodoAccusativeFormsRub {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsRub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-сом.
        /// </summary>
        public static string DodoAccusativeFormsSom {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsSom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-сум.
        /// </summary>
        public static string DodoAccusativeFormsSum {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-тенге.
        /// </summary>
        public static string DodoAccusativeFormsTenge {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsTenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to додо-юань|додо-юанея|додо-юаней.
        /// </summary>
        public static string DodoAccusativeFormsYuan {
            get {
                return ResourceManager.GetString("DodoAccusativeFormsYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно для заполнения.
        /// </summary>
        public static string GlobalValidationMessage {
            get {
                return ResourceManager.GetString("GlobalValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не правильно указаны часы.
        /// </summary>
        public static string IncorrectHourField {
            get {
                return ResourceManager.GetString("IncorrectHourField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не правильно указаны минуты.
        /// </summary>
        public static string IncorrectMinuteField {
            get {
                return ResourceManager.GetString("IncorrectMinuteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh\:mm.
        /// </summary>
        public static string TimeSpanToStringFormat {
            get {
                return ResourceManager.GetString("TimeSpanToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string TimeToStringFormat {
            get {
                return ResourceManager.GetString("TimeToStringFormat", resourceCulture);
            }
        }
    }
}
