//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.RestaurantBoard.Site.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Dodo.RestaurantBoard.Site.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Html_ListenDodoFm {
            get {
                return ResourceManager.GetString("Html_ListenDodoFm", resourceCulture);
            }
        }
        
        public static string OrdersReadinessToStationary {
            get {
                return ResourceManager.GetString("OrdersReadinessToStationary", resourceCulture);
            }
        }
        
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        public static string Title_YouListen {
            get {
                return ResourceManager.GetString("Title_YouListen", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NoConnection {
            get {
                return ResourceManager.GetString("ErrorMessage_NoConnection", resourceCulture);
            }
        }
        
        public static string ExpressProducts {
            get {
                return ResourceManager.GetString("ExpressProducts", resourceCulture);
            }
        }
        
        public static string Making {
            get {
                return ResourceManager.GetString("Making", resourceCulture);
            }
        }
        
        public static string Managed {
            get {
                return ResourceManager.GetString("Managed", resourceCulture);
            }
        }
        
        public static string NotManaged {
            get {
                return ResourceManager.GetString("NotManaged", resourceCulture);
            }
        }
        
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        public static string Title_AccessDenied {
            get {
                return ResourceManager.GetString("Title_AccessDenied", resourceCulture);
            }
        }
        
        public static string NeedToLogin {
            get {
                return ResourceManager.GetString("NeedToLogin", resourceCulture);
            }
        }
        
        public static string ErrorParameterType {
            get {
                return ResourceManager.GetString("ErrorParameterType", resourceCulture);
            }
        }
        
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Title_Exception {
            get {
                return ResourceManager.GetString("Title_Exception", resourceCulture);
            }
        }
        
        public static string Text_Support {
            get {
                return ResourceManager.GetString("Text_Support", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
    }
}
