//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Supplies {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Supplies.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FluidOunceDecrease {
            get {
                return ResourceManager.GetString("FluidOunceDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FluidOunceTitle {
            get {
                return ResourceManager.GetString("FluidOunceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FootDecrease {
            get {
                return ResourceManager.GetString("FootDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FootTitle {
            get {
                return ResourceManager.GetString("FootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GallonDecrease {
            get {
                return ResourceManager.GetString("GallonDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GallonTitle {
            get {
                return ResourceManager.GetString("GallonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлена запись поступления..
        /// </summary>
        public static string Message_AddedSupply {
            get {
                return ResourceManager.GetString("Message_AddedSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлена позиция {0} - {1}, сумма без НДС - {2}, НДС - {3}, Сумма НДС - {4}, сумма с НДС - {5}, цена за ед. - {6}, цена за 1 кг - {7}.
        /// </summary>
        public static string Message_AddedSupplyComposition {
            get {
                return ResourceManager.GetString("Message_AddedSupplyComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалена позиция {0} - {1}, сумма без НДС - {2}, Сумма НДС - {3}, сумма с НДС - {4}, цена за ед. {5}, цена за 1 кг - {6}.
        /// </summary>
        public static string Message_DeletedSupplyComposition {
            get {
                return ResourceManager.GetString("Message_DeletedSupplyComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionCount {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена за 1 кг.: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionPricePerKillogramm {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionPricePerKillogramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена за ед.: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionPricePerPiece {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionPricePerPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма НДС: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionSummaOfVAT {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionSummaOfVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма без НДС: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionSummaWithoutVAT {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionSummaWithoutVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма с НДС: было {0}, стало {1}..
        /// </summary>
        public static string Message_SupplyCompositionSummaWithVAT {
            get {
                return ResourceManager.GetString("Message_SupplyCompositionSummaWithVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция {0}.
        /// </summary>
        public static string Message_SupplyName {
            get {
                return ResourceManager.GetString("Message_SupplyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отредактирована позиция {0} -.
        /// </summary>
        public static string Message_UpdateSupplyComposition {
            get {
                return ResourceManager.GetString("Message_UpdateSupplyComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OunceDecrease {
            get {
                return ResourceManager.GetString("OunceDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OunceTitle {
            get {
                return ResourceManager.GetString("OunceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PoundDecrease {
            get {
                return ResourceManager.GetString("PoundDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PoundTitle {
            get {
                return ResourceManager.GetString("PoundTitle", resourceCulture);
            }
        }
    }
}
