//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Managments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Managments.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От 1 до 2 лет.
        /// </summary>
        public static string AgePizzeriaBetweenOneAndTwoYears {
            get {
                return ResourceManager.GetString("AgePizzeriaBetweenOneAndTwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От 2 до 3 лет.
        /// </summary>
        public static string AgePizzeriaBetweenTwoAndThreeYears {
            get {
                return ResourceManager.GetString("AgePizzeriaBetweenTwoAndThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До 1 года.
        /// </summary>
        public static string AgePizzeriaLessThanYear {
            get {
                return ResourceManager.GetString("AgePizzeriaLessThanYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свыше 3 лет.
        /// </summary>
        public static string AgePizzeriaMoreThreeYears {
            get {
                return ResourceManager.GetString("AgePizzeriaMoreThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        public static string AgePizzeriaUnknow {
            get {
                return ResourceManager.GetString("AgePizzeriaUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BasicUnitOfMeasure {
            get {
                return ResourceManager.GetString("BasicUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исчислять налог с продаж.
        /// </summary>
        public static string CalculateSalesTax {
            get {
                return ResourceManager.GetString("CalculateSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исчислять НДС.
        /// </summary>
        public static string CalculateTax {
            get {
                return ResourceManager.GetString("CalculateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса.
        /// </summary>
        public static string CashBox {
            get {
                return ResourceManager.GetString("CashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть незавершённая кассовая сессия. Необходимо зарыть сессию перед удалением..
        /// </summary>
        public static string CashBoxIsWorking {
            get {
                return ResourceManager.GetString("CashBoxIsWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContainerSize {
            get {
                return ResourceManager.GetString("ContainerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не исчислять налог с продаж.
        /// </summary>
        public static string DontCalculateSalesTax {
            get {
                return ResourceManager.GetString("DontCalculateSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не исчислять НДС.
        /// </summary>
        public static string DontCalculateTax {
            get {
                return ResourceManager.GetString("DontCalculateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DryWeight {
            get {
                return ResourceManager.GetString("DryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to только изображения jpg {0}x{1}.
        /// </summary>
        public static string Error_OnlyJpgImages {
            get {
                return ResourceManager.GetString("Error_OnlyJpgImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плохое время приготовления должно быть большего хорошего.
        /// </summary>
        public static string ErrorMessage_ValidatePreparationBadTimeValue {
            get {
                return ResourceManager.GetString("ErrorMessage_ValidatePreparationBadTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} обязательно для заполнения.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FieldMustBePositive {
            get {
                return ResourceManager.GetString("FieldMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to н.в..
        /// </summary>
        public static string ForNowShort {
            get {
                return ResourceManager.GetString("ForNowShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлен новый праздник.
        /// </summary>
        public static string HolidayCreated {
            get {
                return ResourceManager.GetString("HolidayCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Празник отредактирован.
        /// </summary>
        public static string HolidayEdited {
            get {
                return ResourceManager.GetString("HolidayEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлен новый праздник.
        /// </summary>
        public static string HolidayRemoved {
            get {
                return ResourceManager.GetString("HolidayRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праздник не может быть сохранен, так как есть пересечения с другими праздниками.
        /// </summary>
        public static string HolidaysCannotIntersects {
            get {
                return ResourceManager.GetString("HolidaysCannotIntersects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана организация.
        /// </summary>
        public static string Message_ErrorRequiredOrganization {
            get {
                return ResourceManager.GetString("Message_ErrorRequiredOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, c {1} до {2}, {3}.
        /// </summary>
        public static string OperationalStatisticsStopSaleInformation {
            get {
                return ResourceManager.GetString("OperationalStatisticsStopSaleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        public static string OrganizationType_IPFull {
            get {
                return ResourceManager.GetString("OrganizationType_IPFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИП.
        /// </summary>
        public static string OrganizationType_IPShort {
            get {
                return ResourceManager.GetString("OrganizationType_IPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытое акционерное общество.
        /// </summary>
        public static string OrganizationType_OAOFull {
            get {
                return ResourceManager.GetString("OrganizationType_OAOFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОАО.
        /// </summary>
        public static string OrganizationType_OAOShort {
            get {
                return ResourceManager.GetString("OrganizationType_OAOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общество с ограниченной ответственностью.
        /// </summary>
        public static string OrganizationType_OOOFull {
            get {
                return ResourceManager.GetString("OrganizationType_OOOFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ООО.
        /// </summary>
        public static string OrganizationType_OOOShort {
            get {
                return ResourceManager.GetString("OrganizationType_OOOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытое акционерное общество.
        /// </summary>
        public static string OrganizationType_ZAOFull {
            get {
                return ResourceManager.GetString("OrganizationType_ZAOFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАО.
        /// </summary>
        public static string OrganizationType_ZAOShort {
            get {
                return ResourceManager.GetString("OrganizationType_ZAOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акционерное общество.
        /// </summary>
        public static string OrganizationTypeAB {
            get {
                return ResourceManager.GetString("OrganizationTypeAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string OrganizationTypeABShort {
            get {
                return ResourceManager.GetString("OrganizationTypeABShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акционерное общество.
        /// </summary>
        public static string OrganizationTypeAO {
            get {
                return ResourceManager.GetString("OrganizationTypeAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АО.
        /// </summary>
        public static string OrganizationTypeAOShort {
            get {
                return ResourceManager.GetString("OrganizationTypeAOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акционерное общество.
        /// </summary>
        public static string OrganizationTypeAS {
            get {
                return ResourceManager.GetString("OrganizationTypeAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АО.
        /// </summary>
        public static string OrganizationTypeASShort {
            get {
                return ResourceManager.GetString("OrganizationTypeASShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частная фирма.
        /// </summary>
        public static string OrganizationTypeCHF {
            get {
                return ResourceManager.GetString("OrganizationTypeCHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЧФ.
        /// </summary>
        public static string OrganizationTypeCHFShort {
            get {
                return ResourceManager.GetString("OrganizationTypeCHFShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частный предприниматель.
        /// </summary>
        public static string OrganizationTypeCHP {
            get {
                return ResourceManager.GetString("OrganizationTypeCHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЧП.
        /// </summary>
        public static string OrganizationTypeCHPShort {
            get {
                return ResourceManager.GetString("OrganizationTypeCHPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string OrganizationTypeCorp {
            get {
                return ResourceManager.GetString("OrganizationTypeCorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp..
        /// </summary>
        public static string OrganizationTypeCorpShort {
            get {
                return ResourceManager.GetString("OrganizationTypeCorpShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        public static string OrganizationTypeFIE {
            get {
                return ResourceManager.GetString("OrganizationTypeFIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИП.
        /// </summary>
        public static string OrganizationTypeFIEShort {
            get {
                return ResourceManager.GetString("OrganizationTypeFIEShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Trader.
        /// </summary>
        public static string OrganizationTypeGb_IP {
            get {
                return ResourceManager.GetString("OrganizationTypeGb_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Trader.
        /// </summary>
        public static string OrganizationTypeGb_IPShort {
            get {
                return ResourceManager.GetString("OrganizationTypeGb_IPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoana fizica autorizata.
        /// </summary>
        public static string OrganizationTypeII {
            get {
                return ResourceManager.GetString("OrganizationTypeII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interprindere individuala.
        /// </summary>
        public static string OrganizationTypeIIShort {
            get {
                return ResourceManager.GetString("OrganizationTypeIIShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        public static string OrganizationTypeIL {
            get {
                return ResourceManager.GetString("OrganizationTypeIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IĮ.
        /// </summary>
        public static string OrganizationTypeILShort {
            get {
                return ResourceManager.GetString("OrganizationTypeILShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorporated.
        /// </summary>
        public static string OrganizationTypeInc {
            get {
                return ResourceManager.GetString("OrganizationTypeInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc..
        /// </summary>
        public static string OrganizationTypeIncShort {
            get {
                return ResourceManager.GetString("OrganizationTypeIncShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLLC {
            get {
                return ResourceManager.GetString("OrganizationTypeLLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLLCShort {
            get {
                return ResourceManager.GetString("OrganizationTypeLLCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLLP {
            get {
                return ResourceManager.GetString("OrganizationTypeLLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLLPShort {
            get {
                return ResourceManager.GetString("OrganizationTypeLLPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLtd {
            get {
                return ResourceManager.GetString("OrganizationTypeLtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeLtdShort {
            get {
                return ResourceManager.GetString("OrganizationTypeLtdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Малое предприятие.
        /// </summary>
        public static string OrganizationTypeMB {
            get {
                return ResourceManager.GetString("OrganizationTypeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string OrganizationTypeMBShort {
            get {
                return ResourceManager.GetString("OrganizationTypeMBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОсОО.
        /// </summary>
        public static string OrganizationTypeOsOOShort {
            get {
                return ResourceManager.GetString("OrganizationTypeOsOOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товарищество.
        /// </summary>
        public static string OrganizationTypeOU {
            get {
                return ResourceManager.GetString("OrganizationTypeOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string OrganizationTypeOUShort {
            get {
                return ResourceManager.GetString("OrganizationTypeOUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытая компания с ограниченной ответственностью.
        /// </summary>
        public static string OrganizationTypePLC {
            get {
                return ResourceManager.GetString("OrganizationTypePLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        public static string OrganizationTypePLCShort {
            get {
                return ResourceManager.GetString("OrganizationTypePLCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Societate pe Actiuni.
        /// </summary>
        public static string OrganizationTypeSA {
            get {
                return ResourceManager.GetString("OrganizationTypeSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string OrganizationTypeSAShort {
            get {
                return ResourceManager.GetString("OrganizationTypeSAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeSP {
            get {
                return ResourceManager.GetString("OrganizationTypeSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationTypeSPShort {
            get {
                return ResourceManager.GetString("OrganizationTypeSPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Societate cu Raspundere LImitata.
        /// </summary>
        public static string OrganizationTypeSRL {
            get {
                return ResourceManager.GetString("OrganizationTypeSRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRL.
        /// </summary>
        public static string OrganizationTypeSRLShort {
            get {
                return ResourceManager.GetString("OrganizationTypeSRLShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товарищество с ограниченной ответственностью.
        /// </summary>
        public static string OrganizationTypeTOO {
            get {
                return ResourceManager.GetString("OrganizationTypeTOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОО.
        /// </summary>
        public static string OrganizationTypeTOOShort {
            get {
                return ResourceManager.GetString("OrganizationTypeTOOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытое акционерное общество.
        /// </summary>
        public static string OrganizationTypeUAB {
            get {
                return ResourceManager.GetString("OrganizationTypeUAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAB.
        /// </summary>
        public static string OrganizationTypeUABShort {
            get {
                return ResourceManager.GetString("OrganizationTypeUABShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string PizzaType_Country {
            get {
                return ResourceManager.GetString("PizzaType_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип теста.
        /// </summary>
        public static string PizzaType_DoughType {
            get {
                return ResourceManager.GetString("PizzaType_DoughType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string PizzaType_Name {
            get {
                return ResourceManager.GetString("PizzaType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string PizzaType_Size {
            get {
                return ResourceManager.GetString("PizzaType_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string ProviderConfig_Key {
            get {
                return ResourceManager.GetString("ProviderConfig_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string ProviderConfig_Login {
            get {
                return ResourceManager.GetString("ProviderConfig_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string ProviderConfig_Pass {
            get {
                return ResourceManager.GetString("ProviderConfig_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет.
        /// </summary>
        public static string ProviderConfig_Priority {
            get {
                return ResourceManager.GetString("ProviderConfig_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провайдер.
        /// </summary>
        public static string ProviderConfig_Provider {
            get {
                return ResourceManager.GetString("ProviderConfig_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправитель.
        /// </summary>
        public static string ProviderConfig_Sender {
            get {
                return ResourceManager.GetString("ProviderConfig_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для страны {0} уже есть провайдер с приоритетом {1}.
        /// </summary>
        public static string ProviderConfig_UniqueViolation {
            get {
                return ResourceManager.GetString("ProviderConfig_UniqueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string SocialNetwork_Facebook {
            get {
                return ResourceManager.GetString("SocialNetwork_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string SocialNetwork_Instagram {
            get {
                return ResourceManager.GetString("SocialNetwork_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kroogi.
        /// </summary>
        public static string SocialNetwork_Kroogi {
            get {
                return ResourceManager.GetString("SocialNetwork_Kroogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой Мир.
        /// </summary>
        public static string SocialNetwork_MoyMir {
            get {
                return ResourceManager.GetString("SocialNetwork_MoyMir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноклассники.
        /// </summary>
        public static string SocialNetwork_Odnoklassniki {
            get {
                return ResourceManager.GetString("SocialNetwork_Odnoklassniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renren.
        /// </summary>
        public static string SocialNetwork_Renren {
            get {
                return ResourceManager.GetString("SocialNetwork_Renren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string SocialNetwork_Twitter {
            get {
                return ResourceManager.GetString("SocialNetwork_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вконтакте.
        /// </summary>
        public static string SocialNetwork_Vkontakte {
            get {
                return ResourceManager.GetString("SocialNetwork_Vkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat.
        /// </summary>
        public static string SocialNetwork_WeChat {
            get {
                return ResourceManager.GetString("SocialNetwork_WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weibo.
        /// </summary>
        public static string SocialNetwork_Weibo {
            get {
                return ResourceManager.GetString("SocialNetwork_Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string SocialNetwork_Youtube {
            get {
                return ResourceManager.GetString("SocialNetwork_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор уже добавлен в стоп-лист.
        /// </summary>
        public static string StopList_DeliverySectorIsStopped {
            get {
                return ResourceManager.GetString("StopList_DeliverySectorIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица уже добавлена в стоп-лист.
        /// </summary>
        public static string StopList_DeliveryStreetIsStopped {
            get {
                return ResourceManager.GetString("StopList_DeliveryStreetIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная остановка.
        /// </summary>
        public static string StopSaleFull {
            get {
                return ResourceManager.GetString("StopSaleFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенаправление.
        /// </summary>
        public static string StopSaleWithRedirect {
            get {
                return ResourceManager.GetString("StopSaleWithRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}%.
        /// </summary>
        public static string TaxRateFormat {
            get {
                return ResourceManager.GetString("TaxRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН содержит опечатку.
        /// </summary>
        public static string ValidationError_InnWrongChecksum {
            get {
                return ResourceManager.GetString("ValidationError_InnWrongChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН должен состоять из {0} цифр.
        /// </summary>
        public static string ValidationError_InnWrongFormat {
            get {
                return ResourceManager.GetString("ValidationError_InnWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение должно быть пустым или содержать 12 цифр.
        /// </summary>
        public static string ValidationLength12OnlyDigit {
            get {
                return ResourceManager.GetString("ValidationLength12OnlyDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должно быть заполнено.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно введено значение.
        /// </summary>
        public static string ValidationValueIncorrectly {
            get {
                return ResourceManager.GetString("ValidationValueIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
