//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Shifts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Shifts.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса доставки.
        /// </summary>
        public static string CashBoxStatistic_Delivery {
            get {
                return ResourceManager.GetString("CashBoxStatistic_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агрегатор.
        /// </summary>
        public static string CashBoxStatisticCategory_Aggregator {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Aggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call-центр.
        /// </summary>
        public static string CashBoxStatisticCategory_CallCenter {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменено.
        /// </summary>
        public static string CashBoxStatisticCategory_Cancel {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string CashBoxStatisticCategory_Delivery {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн оплата.
        /// </summary>
        public static string CashBoxStatisticCategory_Online {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самовывоз.
        /// </summary>
        public static string CashBoxStatisticCategory_Pickup {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочено.
        /// </summary>
        public static string CashBoxStatisticCategory_Timeout {
            get {
                return ResourceManager.GetString("CashBoxStatisticCategory_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса ресторана №{0}.
        /// </summary>
        public static string CashBoxStatisticView_Stationary {
            get {
                return ResourceManager.GetString("CashBoxStatisticView_Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to см..
        /// </summary>
        public static string CentimeterDecrease {
            get {
                return ResourceManager.GetString("CentimeterDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сантиметр.
        /// </summary>
        public static string CentimeterTitle {
            get {
                return ResourceManager.GetString("CentimeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to день.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_CanNotRemoveItem {
            get {
                return ResourceManager.GetString("Error_CanNotRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_DeliveryUnitIsInStop {
            get {
                return ResourceManager.GetString("Error_DeliveryUnitIsInStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_SectorIsInStop {
            get {
                return ResourceManager.GetString("Error_SectorIsInStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вечер.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр..
        /// </summary>
        public static string GramDecrease {
            get {
                return ResourceManager.GetString("GramDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грамм.
        /// </summary>
        public static string GramTitle {
            get {
                return ResourceManager.GetString("GramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт..
        /// </summary>
        public static string ItemDecrease {
            get {
                return ResourceManager.GetString("ItemDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to штука.
        /// </summary>
        public static string ItemTitle {
            get {
                return ResourceManager.GetString("ItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кг..
        /// </summary>
        public static string KilogramDecrease {
            get {
                return ResourceManager.GetString("KilogramDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to килограмм.
        /// </summary>
        public static string KilogramTitle {
            get {
                return ResourceManager.GetString("KilogramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л..
        /// </summary>
        public static string LiterDecrease {
            get {
                return ResourceManager.GetString("LiterDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to литр.
        /// </summary>
        public static string LiterTitle {
            get {
                return ResourceManager.GetString("LiterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м..
        /// </summary>
        public static string MeterDecrease {
            get {
                return ResourceManager.GetString("MeterDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to метр.
        /// </summary>
        public static string MeterTitle {
            get {
                return ResourceManager.GetString("MeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мл..
        /// </summary>
        public static string MilliliterDecrease {
            get {
                return ResourceManager.GetString("MilliliterDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллилитр.
        /// </summary>
        public static string MilliliterTitle {
            get {
                return ResourceManager.GetString("MilliliterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мм..
        /// </summary>
        public static string MillimeterDecrease {
            get {
                return ResourceManager.GetString("MillimeterDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиметр.
        /// </summary>
        public static string MillimeterTitle {
            get {
                return ResourceManager.GetString("MillimeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to утро.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ночь.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Oven {
            get {
                return ResourceManager.GetString("Oven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OvenCleaning {
            get {
                return ResourceManager.GetString("OvenCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смены не могут пересекаться.
        /// </summary>
        public static string ShiftsCanNotCross {
            get {
                return ResourceManager.GetString("ShiftsCanNotCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_InternetProblems {
            get {
                return ResourceManager.GetString("StopListReason_InternetProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_LackOfCouriers {
            get {
                return ResourceManager.GetString("StopListReason_LackOfCouriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_LackOfKitchenWorkers {
            get {
                return ResourceManager.GetString("StopListReason_LackOfKitchenWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_PizzeriaRepairment {
            get {
                return ResourceManager.GetString("StopListReason_PizzeriaRepairment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_PowerOutage {
            get {
                return ResourceManager.GetString("StopListReason_PowerOutage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopListReason_TechnicalIssues {
            get {
                return ResourceManager.GetString("StopListReason_TechnicalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopSale {
            get {
                return ResourceManager.GetString("StopSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to т..
        /// </summary>
        public static string TonDecrease {
            get {
                return ResourceManager.GetString("TonDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тонна.
        /// </summary>
        public static string TonTitle {
            get {
                return ResourceManager.GetString("TonTitle", resourceCulture);
            }
        }
    }
}
