//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.OrdersProcessing {
	/// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.OrdersProcessing.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменен.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Десерты.
        /// </summary>
        public static string CategoryDesserts {
            get {
                return ResourceManager.GetString("CategoryDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напитки.
        /// </summary>
        public static string CategoryDrinks {
            get {
                return ResourceManager.GetString("CategoryDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары.
        /// </summary>
        public static string CategoryGoods {
            get {
                return ResourceManager.GetString("CategoryGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пицца.
        /// </summary>
        public static string CategoryPizza {
            get {
                return ResourceManager.GetString("CategoryPizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соусы.
        /// </summary>
        public static string CategorySauces {
            get {
                return ResourceManager.GetString("CategorySauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закуски.
        /// </summary>
        public static string CategorySnacks {
            get {
                return ResourceManager.GetString("CategorySnacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брак.
        /// </summary>
        public static string DefectiveProduct {
            get {
                return ResourceManager.GetString("DefectiveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставлен.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню доставки.
        /// </summary>
        public static string DeliveryMenu {
            get {
                return ResourceManager.GetString("DeliveryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;b&gt;(дубль)&lt;/b&gt;.
        /// </summary>
        public static string DuplicateOrderLine {
            get {
                return ResourceManager.GetString("DuplicateOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задана размерная характеристика.
        /// </summary>
        public static string Error_EmptyDimensionalCharacteristics {
            get {
                return ResourceManager.GetString("Error_EmptyDimensionalCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное количество.
        /// </summary>
        public static string Error_Number {
            get {
                return ResourceManager.GetString("Error_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пищевой.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендации.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Халяльное.
        /// </summary>
        public static string Halal {
            get {
                return ResourceManager.GetString("Halal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полухаляльное.
        /// </summary>
        public static string HalfHalal {
            get {
                return ResourceManager.GetString("HalfHalal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На доставке.
        /// </summary>
        public static string InDelivery {
            get {
                return ResourceManager.GetString("InDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печь.
        /// </summary>
        public static string InOven {
            get {
                return ResourceManager.GetString("InOven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка.
        /// </summary>
        public static string MenuAccessibility_Delivery {
            get {
                return ResourceManager.GetString("MenuAccessibility_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питание персонала.
        /// </summary>
        public static string MenuAccessibility_Personal {
            get {
                return ResourceManager.GetString("MenuAccessibility_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ресторан.
        /// </summary>
        public static string MenuAccessibility_Stationary {
            get {
                return ResourceManager.GetString("MenuAccessibility_Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя забраковать продукт, заказу которого больше 2-х дней.
        /// </summary>
        public static string MessageError_FailedDefectOrderLineMoreTwoDaysAgo {
            get {
                return ResourceManager.GetString("MessageError_FailedDefectOrderLineMoreTwoDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя вернуть продукт на кухню. Истек срок приготовления..
        /// </summary>
        public static string MessageError_PreparationTimeLimitExpired {
            get {
                return ResourceManager.GetString("MessageError_PreparationTimeLimitExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на непищевой.
        /// </summary>
        public static string Nonfood {
            get {
                return ResourceManager.GetString("Nonfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинка (Холодная линия).
        /// </summary>
        public static string OnColdAssemblyTable {
            get {
                return ResourceManager.GetString("OnColdAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесто.
        /// </summary>
        public static string OnDoughTable {
            get {
                return ResourceManager.GetString("OnDoughTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинка (Горячая линия).
        /// </summary>
        public static string OnHotAssemblyTable {
            get {
                return ResourceManager.GetString("OnHotAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упаковка.
        /// </summary>
        public static string OnPackingTable {
            get {
                return ResourceManager.GetString("OnPackingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка.
        /// </summary>
        public static string OrderType_Delivery {
            get {
                return ResourceManager.GetString("OrderType_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дос.
        /// </summary>
        public static string OrderType_DeliveryShortAlias {
            get {
                return ResourceManager.GetString("OrderType_DeliveryShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перс.
        /// </summary>
        public static string OrderType_PersonaFoodShortAlias {
            get {
                return ResourceManager.GetString("OrderType_PersonaFoodShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питание персонала.
        /// </summary>
        public static string OrderType_PersonalFood {
            get {
                return ResourceManager.GetString("OrderType_PersonalFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самовывоз.
        /// </summary>
        public static string OrderType_Pickup {
            get {
                return ResourceManager.GetString("OrderType_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СВ.
        /// </summary>
        public static string OrderType_PickupShortAlias {
            get {
                return ResourceManager.GetString("OrderType_PickupShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пополнение витрины.
        /// </summary>
        public static string OrderType_ShopWindowSupply {
            get {
                return ResourceManager.GetString("OrderType_ShopWindowSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кус.
        /// </summary>
        public static string OrderType_ShopWindowSupplyShortAlias {
            get {
                return ResourceManager.GetString("OrderType_ShopWindowSupplyShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ресторан.
        /// </summary>
        public static string OrderType_Stationary {
            get {
                return ResourceManager.GetString("OrderType_Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зал.
        /// </summary>
        public static string OrderType_StationaryShortAlias {
            get {
                return ResourceManager.GetString("OrderType_StationaryShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню для персонала.
        /// </summary>
        public static string PersonalMenu {
            get {
                return ResourceManager.GetString("PersonalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема для пицц.
        /// </summary>
        public static string PizzaScheme {
            get {
                return ResourceManager.GetString("PizzaScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высокий.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Низкий.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидает приготовления.
        /// </summary>
        public static string ProductionStage_WaitingMake {
            get {
                return ResourceManager.GetString("ProductionStage_WaitingMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню ресторана.
        /// </summary>
        public static string RestaurantMenu {
            get {
                return ResourceManager.GetString("RestaurantMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема для сэндвичей.
        /// </summary>
        public static string SandwichScheme {
            get {
                return ResourceManager.GetString("SandwichScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема без производства.
        /// </summary>
        public static string SimpleScheme {
            get {
                return ResourceManager.GetString("SimpleScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема для закусок.
        /// </summary>
        public static string SnacksScheme {
            get {
                return ResourceManager.GetString("SnacksScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Т.
        /// </summary>
        public static string ThinDoughAlias {
            get {
                return ResourceManager.GetString("ThinDoughAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выпечка.
        /// </summary>
        public static string TypeBaked {
            get {
                return ResourceManager.GetString("TypeBaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составной.
        /// </summary>
        public static string TypeComposite {
            get {
                return ResourceManager.GetString("TypeComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простой.
        /// </summary>
        public static string TypeSimple {
            get {
                return ResourceManager.GetString("TypeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определено.
        /// </summary>
        public static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на доставку.
        /// </summary>
        public static string ValidateMessage_Delivery {
            get {
                return ResourceManager.GetString("ValidateMessage_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на питание персонала.
        /// </summary>
        public static string ValidateMessage_PersonalFood {
            get {
                return ResourceManager.GetString("ValidateMessage_PersonalFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на самовывоз.
        /// </summary>
        public static string ValidateMessage_Pickup {
            get {
                return ResourceManager.GetString("ValidateMessage_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кусочки.
        /// </summary>
        public static string ValidateMessage_ShopWindowSupply {
            get {
                return ResourceManager.GetString("ValidateMessage_ShopWindowSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стационар.
        /// </summary>
        public static string ValidateMessage_Stationary {
            get {
                return ResourceManager.GetString("ValidateMessage_Stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидает поступления на склад.
        /// </summary>
        public static string WaitIncomingsOnWarehouse {
            get {
                return ResourceManager.GetString("WaitIncomingsOnWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидает отправки.
        /// </summary>
        public static string WaitingDelivery {
            get {
                return ResourceManager.GetString("WaitingDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидание.
        /// </summary>
        public static string WaitingMake {
            get {
                return ResourceManager.GetString("WaitingMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без особенностей.
        /// </summary>
        public static string WithoutSpecialization {
            get {
                return ResourceManager.GetString("WithoutSpecialization", resourceCulture);
            }
        }
    }
}
