//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodo.Core.Resources.Motivation {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodo.Core.Resources.Motivation.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату начала.
        /// </summary>
        public static string BeginDateRequired {
            get {
                return ResourceManager.GetString("BeginDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий не должен превышать 500 символов.
        /// </summary>
        public static string ClientMessage_AddressDescriptionTooLong {
            get {
                return ResourceManager.GetString("ClientMessage_AddressDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните все поля адреса..
        /// </summary>
        public static string ClientMessage_AddressInvalid {
            get {
                return ResourceManager.GetString("ClientMessage_AddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный адрес не входит в зону доставки..
        /// </summary>
        public static string ClientMessage_AddressIsNotIncludedInDeliveryArea {
            get {
                return ResourceManager.GetString("ClientMessage_AddressIsNotIncludedInDeliveryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, в указанное вами время пиццерия работать не будет. Время работы пиццерии с {0} по {1}.
        /// </summary>
        public static string ClientMessage_DelayedOrderTime {
            get {
                return ResourceManager.GetString("ClientMessage_DelayedOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите другое время доставки. Мы не можем доставить заказ в указанное вами время..
        /// </summary>
        public static string ClientMessage_DelayedOrderTimeInvalid {
            get {
                return ResourceManager.GetString("ClientMessage_DelayedOrderTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа доставки приостановлена. Приносим наши извинения.
        /// </summary>
        public static string ClientMessage_DeliveryStop {
            get {
                return ResourceManager.GetString("ClientMessage_DeliveryStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша корзина пуста.
        /// </summary>
        public static string ClientMessage_EmptyBasket {
            get {
                return ResourceManager.GetString("ClientMessage_EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите бесплатные соусы.
        /// </summary>
        public static string ClientMessage_InvalidFreeSauces {
            get {
                return ResourceManager.GetString("ClientMessage_InvalidFreeSauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите с какой суммы нам подготовить сдачу. Она должна быть не меньше суммы заказа..
        /// </summary>
        public static string ClientMessage_NoteEmpty {
            get {
                return ResourceManager.GetString("ClientMessage_NoteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cумма, с которой подготовить сдачу, должна быть не меньше суммы заказа..
        /// </summary>
        public static string ClientMessage_NoteInvalid {
            get {
                return ResourceManager.GetString("ClientMessage_NoteInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная сумма заказа - {0}.
        /// </summary>
        public static string ClientMessage_OrderCostInvalid {
            get {
                return ResourceManager.GetString("ClientMessage_OrderCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пиццерию, из которой хотите забрать заказ.
        /// </summary>
        public static string ClientMessage_PickupPizzeriaEmpty {
            get {
                return ResourceManager.GetString("ClientMessage_PickupPizzeriaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, не удалось оплатить заказ. Пиццерия закрыта..
        /// </summary>
        public static string ClientMessage_PizzeriaIsClosed {
            get {
                return ResourceManager.GetString("ClientMessage_PizzeriaIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, {0} нет в наличии. Пожалуйста, удалите этот продукт из корзины..
        /// </summary>
        public static string ClientMessage_ProductInStopList {
            get {
                return ResourceManager.GetString("ClientMessage_ProductInStopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату окончания.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вечерняя смена.
        /// </summary>
        public static string EveningShift {
            get {
                return ResourceManager.GetString("EveningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное имя.
        /// </summary>
        public static string Message__ClientNameTooLong {
            get {
                return ResourceManager.GetString("Message__ClientNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное описание адреса.
        /// </summary>
        public static string Message_AddressDescriptionTooLong {
            get {
                return ResourceManager.GetString("Message_AddressDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введен адрес.
        /// </summary>
        public static string Message_AddressEmpty {
            get {
                return ResourceManager.GetString("Message_AddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный адрес.
        /// </summary>
        public static string Message_AddressInvalid {
            get {
                return ResourceManager.GetString("Message_AddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес не входит в зону доставки.
        /// </summary>
        public static string Message_AddressIsNotIncludedInDeliveryArea {
            get {
                return ResourceManager.GetString("Message_AddressIsNotIncludedInDeliveryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введен данные о клиенте.
        /// </summary>
        public static string Message_ClientEmpty {
            get {
                return ResourceManager.GetString("Message_ClientEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент в черном списке.
        /// </summary>
        public static string Message_ClientFromBlackList {
            get {
                return ResourceManager.GetString("Message_ClientFromBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введено имя.
        /// </summary>
        public static string Message_ClientNameEmpty {
            get {
                return ResourceManager.GetString("Message_ClientNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, в указанное вами время пиццерия работать не будет. Время работы пиццерии с {0} по {1}.
        /// </summary>
        public static string Message_DelayedOrderTime {
            get {
                return ResourceManager.GetString("Message_DelayedOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное время отложенного заказа.
        /// </summary>
        public static string Message_DelayedOrderTimeInvalid {
            get {
                return ResourceManager.GetString("Message_DelayedOrderTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В отложенном заказе отсутствует время..
        /// </summary>
        public static string Message_DelayedOrderWithoutTime {
            get {
                return ResourceManager.GetString("Message_DelayedOrderWithoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа доставки приостановлена.
        /// </summary>
        public static string Message_DeliveryStop {
            get {
                return ResourceManager.GetString("Message_DeliveryStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пустая.
        /// </summary>
        public static string Message_EmptyBasket {
            get {
                return ResourceManager.GetString("Message_EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнена корзина.
        /// </summary>
        public static string Message_EmptyComposition {
            get {
                return ResourceManager.GetString("Message_EmptyComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введен номер дома.
        /// </summary>
        public static string Message_EmptyHouse {
            get {
                return ResourceManager.GetString("Message_EmptyHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введена улица.
        /// </summary>
        public static string Message_EmptyStreetName {
            get {
                return ResourceManager.GetString("Message_EmptyStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное время отложенного заказа..
        /// </summary>
        public static string Message_IncorrectDelayedTime {
            get {
                return ResourceManager.GetString("Message_IncorrectDelayedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма обеда превышает максимально допустимое значение..
        /// </summary>
        public static string Message_IncorrectPersonalOrderSum {
            get {
                return ResourceManager.GetString("Message_IncorrectPersonalOrderSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны бесплатные соусы.
        /// </summary>
        public static string Message_InvalidFreeSauces {
            get {
                return ResourceManager.GetString("Message_InvalidFreeSauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, вы превысили максимальную сумму для оплаты наличными на сайте..
        /// </summary>
        public static string Message_MaxCashPaymentLimitExceeded {
            get {
                return ResourceManager.GetString("Message_MaxCashPaymentLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны продукты для обеда..
        /// </summary>
        public static string Message_NotChoosedProducts {
            get {
                return ResourceManager.GetString("Message_NotChoosedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введена купюра.
        /// </summary>
        public static string Message_NoteEmpty {
            get {
                return ResourceManager.GetString("Message_NoteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно введена купюра.
        /// </summary>
        public static string Message_NoteInvalid {
            get {
                return ResourceManager.GetString("Message_NoteInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данный момент продукт {0} не продается.
        /// </summary>
        public static string Message_NowPproductIsNotForSale {
            get {
                return ResourceManager.GetString("Message_NowPproductIsNotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа (без учёта сувениров) ниже минимальной.
        /// </summary>
        public static string Message_OrderCostInvalid {
            get {
                return ResourceManager.GetString("Message_OrderCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя оформить отложенный обед, если в нём нет продуктов с кухни.
        /// </summary>
        public static string Message_OrderWithSimpleProductsOnly {
            get {
                return ResourceManager.GetString("Message_OrderWithSimpleProductsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пиццерию, из которой забирать заказ.
        /// </summary>
        public static string Message_PickupPizzeriaEmpty {
            get {
                return ResourceManager.GetString("Message_PickupPizzeriaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиццерия не работает.
        /// </summary>
        public static string Message_PizzeriaIsClosed {
            get {
                return ResourceManager.GetString("Message_PizzeriaIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена пиццерии не открыта. Пожалуйста, обратитесь к менеджеру смены.
        /// </summary>
        public static string Message_PizzeriaShiftIsClosed {
            get {
                return ResourceManager.GetString("Message_PizzeriaShiftIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, пиццерия не готовит заказы на {0}.
        /// </summary>
        public static string Message_PizzeriaWorkTypeDisabled {
            get {
                return ResourceManager.GetString("Message_PizzeriaWorkTypeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт в стоп листе: {0}.
        /// </summary>
        public static string Message_ProductInStopList {
            get {
                return ResourceManager.GetString("Message_ProductInStopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт {0} не входит в меню.
        /// </summary>
        public static string Message_ProductIsNotOnMenu {
            get {
                return ResourceManager.GetString("Message_ProductIsNotOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось забраковать заказ.
        /// </summary>
        public static string Message_RemakeDefectedOrderFailed {
            get {
                return ResourceManager.GetString("Message_RemakeDefectedOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа ресторана приостановлена.
        /// </summary>
        public static string Message_StationaryStop {
            get {
                return ResourceManager.GetString("Message_StationaryStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введен номер телефона.
        /// </summary>
        public static string Message_TelephoneEmpty {
            get {
                return ResourceManager.GetString("Message_TelephoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утренняя смена.
        /// </summary>
        public static string MorningShift {
            get {
                return ResourceManager.GetString("MorningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночная смена.
        /// </summary>
        public static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принят.
        /// </summary>
        public static string OrderState_Accepted {
            get {
                return ResourceManager.GetString("OrderState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнен.
        /// </summary>
        public static string OrderState_Completed {
            get {
                return ResourceManager.GetString("OrderState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактируется.
        /// </summary>
        public static string OrderState_Editing {
            get {
                return ResourceManager.GetString("OrderState_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        public static string OrderState_Failure {
            get {
                return ResourceManager.GetString("OrderState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string OrderState_Kitchen {
            get {
                return ResourceManager.GetString("OrderState_Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string OrderState_OnDelivery {
            get {
                return ResourceManager.GetString("OrderState_OnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакован.
        /// </summary>
        public static string OrderState_OnTheShelf {
            get {
                return ResourceManager.GetString("OrderState_OnTheShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенаправлен.
        /// </summary>
        public static string OrderState_Redirect {
            get {
                return ResourceManager.GetString("OrderState_Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторно.
        /// </summary>
        public static string OrderState_Storno {
            get {
                return ResourceManager.GetString("OrderState_Storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочен.
        /// </summary>
        public static string OrderState_TimeOut {
            get {
                return ResourceManager.GetString("OrderState_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определен.
        /// </summary>
        public static string OrderState_Unknow {
            get {
                return ResourceManager.GetString("OrderState_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брак.
        /// </summary>
        public static string Source_DefectOrder {
            get {
                return ResourceManager.GetString("Source_DefectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильное приложение.
        /// </summary>
        public static string Source_Mobile {
            get {
                return ResourceManager.GetString("Source_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиццерия.
        /// </summary>
        public static string Source_Pizzeria {
            get {
                return ResourceManager.GetString("Source_Pizzeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторан.
        /// </summary>
        public static string Source_Restaurant {
            get {
                return ResourceManager.GetString("Source_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string Source_Site {
            get {
                return ResourceManager.GetString("Source_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Source_Telephone {
            get {
                return ResourceManager.GetString("Source_Telephone", resourceCulture);
            }
        }
    }
}
